const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const context=vm.createContext({console,Math,Set,JSON});
vm.runInContext(fs.readFileSync(path.join(root,'src/core.js'),'utf8')+'\nthis.Loto=Loto;',context);
const L=context.Loto;let passed=0;
function test(name,fn){fn();console.log('✓ '+name);passed++;}
const p=L.demo();
test('Демо: 3 классических билета, 4 типа, валидный проект',()=>{assert.equal(L.validate(p).length,0);assert.equal(p.tickets.length,3);assert.equal(new Set(p.questions.map(q=>q.type)).size,4);});
test('Случайный выбор без повторения билетов',()=>{for(let i=0;i<100;i++){const s=new L.Session(p,3);assert.equal(new Set(s.tickets.map(t=>t.id)).size,3);assert.equal(s.total,45);}});
test('Один ответ: успех начисляется только один раз',()=>{const s=new L.Session(p,1),q=p.questions[0],a=q.options.find(o=>o.correct).id;assert.equal(s.check('cell',q,a),'correct');assert.equal(s.check('cell',q,a),'blocked');assert.equal(s.done.size,1);});
test('Ошибка: двойная проверка не снимает две жизни',()=>{const s=new L.Session(p,1),q=p.questions[0],a=q.options.find(o=>!o.correct).id;assert.equal(s.check('cell',q,a),'wrong');assert.equal(s.check('cell',q,a),'blocked');assert.equal(s.lives,2);assert.equal(s.errors,1);});
test('Пустой ответ не снимает жизнь',()=>{const s=new L.Session(p,1);assert.equal(s.check('cell',p.questions[0],''),'empty');assert.equal(s.lives,3);});
test('Множественный выбор: только точный набор',()=>{const q=p.questions.find(q=>q.type==='multiple'),a=q.options.filter(o=>o.correct).map(o=>o.id);assert.equal(L.correct(q,a),true);assert.equal(L.correct(q,a.slice(1)),false);assert.equal(L.correct(q,[...a,q.options.find(o=>!o.correct).id]),false);});
test('Ввод: пробелы, регистр, е/ё и альтернативы',()=>{const q={type:'text',answers:['зелёный чай','чай'],yo:true,spaces:true,caseSensitive:false};assert.equal(L.correct(q,'  ЗЕЛЕНЫЙ   ЧАЙ  '),true);assert.equal(L.correct(q,'Чай'),true);q.caseSensitive=true;assert.equal(L.correct(q,'Чай'),false);});
test('Порядок: последовательность идентификаторов',()=>{const q=p.questions.find(q=>q.type==='order'),a=q.options.map(o=>o.id);assert.equal(L.correct(q,a),true);assert.equal(L.correct(q,[...a].reverse()),false);});
test('Поражение блокирует дальнейшие ответы',()=>{const s=new L.Session(p,1),q=p.questions[0],wrong=q.options.find(o=>!o.correct).id;for(let i=0;i<3;i++)s.check('cell'+i,q,wrong);assert.equal(s.status,'lose');assert.equal(s.lives,0);assert.equal(s.check('cell4',q,q.options[0].id),'blocked');});
test('Победа на всех выбранных билетах',()=>{const s=new L.Session(p,3);for(const t of s.tickets)t.cells.forEach((id,i)=>{if(!id)return;const q=p.questions.find(q=>q.id===id),a=q.type==='text'?q.answers[0]:q.type==='single'?q.options.find(o=>o.correct).id:q.type==='multiple'?q.options.filter(o=>o.correct).map(o=>o.id):q.options.map(o=>o.id);assert.equal(s.check(t.id+':'+i,q,a),'correct');});assert.equal(s.status,'win');assert.equal(s.done.size,45);});
test('Одинаковые видимые ответы не подменяют ID',()=>{const q=L.question(1),other=L.question(1);assert.equal(L.correct(q,other.options[0].id),false);});
test('Повторное задание считается отдельно в каждой клетке',()=>{const s=new L.Session(p,1),q=p.questions[0];s.check('a',q,q.options[0].id);s.check('b',q,q.options[0].id);assert.equal(s.done.size,2);});
test('Повреждённые ссылки и неверные версии отклоняются',()=>{const bad=L.clone(p);bad.tickets[0].cells[0]='missing';assert.ok(L.validate(bad).length);bad.version=2;assert.ok(L.validate(bad).length);});
test('Невозможный диапазон и некорректные ответы отклоняются',()=>{const bad=L.clone(p);bad.rules.max=6;bad.questions[0].options.forEach(o=>o.correct=false);assert.ok(L.validate(bad).length>=2);});
test('Импорт не допускает внешние изображения и CSS-инъекции',()=>{const bad=L.clone(p);bad.design.background='https://example.com/a.png';bad.design.table='red;display:none';assert.ok(L.validate(bad).length>=2);});
test('Сохранение JSON сохраняет содержание и связи',()=>assert.equal(JSON.stringify(JSON.parse(JSON.stringify(p))),JSON.stringify(p)));
vm.runInContext(fs.readFileSync(path.join(root,'src/export.js'),'utf8')+'\nthis.makeHTML=makeHTML;',context);
test('Экспорт — автономный HTML без внешних подключений',()=>{const html=context.makeHTML(p);assert.ok(html.includes('class LotoGame'));assert.ok(!/src="https?:|href="https?:/.test(html));const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,1);new vm.Script(scripts[0][1]);});
test('Учительский текст не может закрыть script в экспорте',()=>{const bad=L.clone(p);bad.title='</script><script>alert(1)</script>';const html=context.makeHTML(bad);assert.equal([...html.matchAll(/<script>/g)].length,1);assert.ok(html.includes('\\u003c/script>'));});
fs.writeFileSync(path.join(root,'exports/Демонстрационный проект.loto.json'),JSON.stringify(p,null,2));
fs.writeFileSync(path.join(root,'exports/Математическое лото.html'),context.makeHTML(p));
const optimized=L.clone(p);optimized.questions=optimized.questions.filter(q=>new Set(optimized.tickets.flatMap(t=>t.cells)).has(q.id));
fs.writeFileSync(path.join(root,'exports/Математическое лото — облегчённое.html'),context.makeHTML(optimized));
console.log('\nПройдено '+passed+' проверок.');
