const LotoCellDrag=(()=>{
  let active=false,suppressUntil=0;
  document.addEventListener('click',event=>{if(Date.now()<suppressUntil&&event.target.closest?.('[data-cell],[data-mini-cell]')){event.preventDefault();event.stopImmediatePropagation();}},true);
  function bind(container,selector,position,move,beforeDrag=()=>{}){container.querySelectorAll(selector).forEach(cell=>{cell.draggable=false;cell.ondragstart=e=>e.preventDefault();cell.onkeydown=e=>{if(!e.altKey||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const from=position(cell),delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-from.cols,ArrowDown:from.cols}[e.key];e.preventDefault();if((e.key==='ArrowLeft'&&from.index%from.cols===0)||(e.key==='ArrowRight'&&from.index%from.cols===from.cols-1))return;move(from,{...from,index:from.index+delta});};let start=null,target=null,ghost=null;
    cell.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0)return;start={x:e.clientX,y:e.clientY,from:position(cell)};target=null;cell.setPointerCapture?.(e.pointerId);};
    cell.onpointermove=e=>{if(!start)return;if(!active&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<8)return;e.preventDefault();if(!active){active=true;beforeDrag();cell.classList.add('drag-source');const r=cell.getBoundingClientRect();ghost=cell.cloneNode(true);ghost.removeAttribute('id');ghost.classList.add('cell-drag-ghost');ghost.style.cssText=`position:fixed;width:${r.width}px;height:${r.height}px;left:0;top:0;pointer-events:none;z-index:1000;`;if(typeof getComputedStyle==='function'){const style=getComputedStyle(cell);ghost.style.background=style.backgroundColor;ghost.style.color=style.color;ghost.style.font=style.font;}document.body.append(ghost);}if(ghost)ghost.style.transform=`translate(${e.clientX+12}px,${e.clientY+12}px) rotate(3deg)`;target?.classList.remove('drop-target');const hit=document.elementFromPoint?.(e.clientX,e.clientY)?.closest(selector);target=hit&&container.contains(hit)?hit:null;target?.classList.add('drop-target');};
    const finish=(e,cancel=false)=>{if(!start)return;const from=start.from,to=target&&position(target),dragging=active;start=null;target?.classList.remove('drop-target');cell.classList.remove('drag-source');ghost?.remove();ghost=null;target=null;active=false;if(dragging){suppressUntil=Date.now()+250;e.preventDefault();if(!cancel&&to)move(from,to);}};
    cell.onpointerup=e=>finish(e);cell.onpointercancel=e=>finish(e,true);
  });}
  function unbind(container,selector){container.querySelectorAll(selector).forEach(cell=>{for(const event of ['onpointerdown','onpointermove','onpointerup','onpointercancel','ondragstart','onkeydown'])cell[event]=null;});}
  return {bind,unbind,get active(){return active;}};
})();
