'use strict';
const Loto = (() => {
const clone = x => JSON.parse(JSON.stringify(x));
const uid = () => 'id-' + Math.random().toString(36).slice(2,11);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle = a => {a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const types = {single:'Один ответ',multiple:'Несколько ответов',text:'Ввод ответа',order:'По порядку',audio:'Аудиозадание',passage:'Готовый текст'};
function question(n=1){return {id:uid(),type:'single',showDetails:true,answerRequired:true,labelMedia:{image:''},text:`Сколько будет ${n} + ${n}?`,label:`${n} + ${n}`,stamp:String(n*2),explanation:`${n} + ${n} = ${n*2}`,options:[{id:uid(),text:String(n*2),correct:true},{id:uid(),text:String(n*2+1),correct:false},{id:uid(),text:String(n*2-1),correct:false}],answers:[String(n*2)],caseSensitive:false,yo:true,spaces:true};}
function demo(){const questions=Array.from({length:15},(_,i)=>question(i+1));
Object.assign(questions[3],{type:'multiple',text:'Выберите все чётные числа.',label:'Чётные числа',stamp:'2, 4',explanation:'Чётные числа делятся на 2 без остатка.',options:[{id:uid(),text:'2',correct:true},{id:uid(),text:'3',correct:false},{id:uid(),text:'4',correct:true}]});
Object.assign(questions[7],{type:'text',text:'Как называется результат сложения?',label:'Результат сложения',stamp:'Сумма',answers:['сумма'],explanation:'Результат сложения — сумма.'});
Object.assign(questions[11],{type:'order',text:'Расположите числа от меньшего к большему.',label:'По возрастанию',stamp:'1 → 5',options:['1','3','5'].map(text=>({id:uid(),text,correct:false})),explanation:'1 меньше 3, а 3 меньше 5.'});
questions[14].text='В школьной библиотеке на первой полке стояло 15 книг о природе, а на второй — ещё 15 книг о путешествиях. Сколько всего книг стояло на этих двух полках? Выберите бочонок с правильным ответом.';
const masks=[[0,2,4,6,8],[1,2,3,5,7],[0,3,4,6,8]];
return {version:1,language:'ru',editorLanguage:'ru',title:'Математическое лото',description:'Решай задания, выбирай бочонки и собери свой счастливый билет!',questions,tickets:Array.from({length:3},(_,t)=>({id:uid(),name:`Билет ${t+1}`,rows:3,cols:9,template:'classic',cells:Array.from({length:27},(_,i)=>masks[Math.floor(i/9)].includes(i%9)?questions[(Math.floor(i/9)*5+masks[Math.floor(i/9)].indexOf(i%9)+t*3)%15].id:null)})),rules:{lives:3,min:1,max:3,emoji:'❤️',lifeFormat:'repeat',faded:true},design:{table:'#155849',accent:'#dcb571',font:'Georgia',background:'',fit:'cover',dim:15,position:'center',ticket:'#fff8e8',ink:'#3a3024',cell:'#fffaf0',barrel:'#edcb8c',radius:12,fontSize:18,questionSize:22,answerSize:22,barrelSize:80,titleSize:47,instructionSize:14,chooseSize:14,tableOpacity:0,selected:'#dcae59',correct:'#56ad81',wrong:'#ed7177',button:'#e4bd77',buttonText:'#322416',checkLabel:'Проверить',modal:'#fffaf0',questionColor:'#3a3024',answerColor:'#3a3024',barrelSkin:'oak',barrelImage:'',answerAnimation:'fade',animationDuration:350},hero:{image:'',show:true,name:'',placement:'both',nameSize:13,lineSize:14,lines:{},x:85,y:75,size:90,opacity:100,flip:false,effect:'glow',color:'#ffd782',duration:1,intensity:15,hover:true,correct:true,wrong:false,win:true},screens:{winTitle:'Блестящая победа!',winText:'Все бочонки на своих местах. Отличная работа!',loseTitle:'Попробуем ещё раз?',loseText:'Каждая попытка делает тебя сильнее.',startButton:'Начать игру',again:'Играть снова'}};}
function normalize(s,q){s=String(s).trim();if(!q.caseSensitive)s=s.toLocaleLowerCase();if(q.yo)s=s.replace(/ё/g,'е').replace(/Ё/g,'Е');if(q.spaces)s=s.replace(/\s+/g,' ');return s;}
function correct(q,a){if(q.type==='passage'||q.type==='audio'&&q.answerRequired===false)return false;if(q.type==='text')return q.answers.some(s=>normalize(s,q)===normalize(a,q));if(q.type==='single'||q.type==='audio')return q.options.some(o=>o.id===a&&o.correct);if(q.type==='multiple')return JSON.stringify([...a].sort())===JSON.stringify(q.options.filter(o=>o.correct).map(o=>o.id).sort());return JSON.stringify(a)===JSON.stringify(q.options.map(o=>o.id));}
function validate(p){const errors=[];if(!p||p.version!==1)return ['Неподдерживаемая версия проекта. Нужна версия 1.'];
if(typeof p.title!=='string'||typeof p.description!=='string')return ['Отсутствует название или описание проекта.'];
if(!Array.isArray(p.questions)||!Array.isArray(p.tickets)||!p.rules||!p.design||!p.hero||!p.screens)return ['Повреждена структура проекта.'];
if(p.questions.length>1000||p.tickets.length>100)return ['Слишком большой проект.'];
for(const key of ['winTitle','winText','loseTitle','loseText','startButton','again'])if(typeof p.screens[key]!=='string')errors.push('Повреждены тексты экранов.');
const limits={radius:[0,24],fontSize:[10,30],dim:[0,80]};for(const [key,[min,max]] of Object.entries(limits))if(!Number.isFinite(p.design[key])||p.design[key]<min||p.design[key]>max)errors.push('Неверное значение оформления: '+key);
if(!['cover','contain','repeat'].includes(p.design.fit)||!['center','top','bottom','left','right'].includes(p.design.position))errors.push('Некорректное положение фона.');
if(typeof p.rules.emoji!=='string'||typeof p.design.checkLabel!=='string')errors.push('Некорректные подписи игры.');
for(const [key,min,max] of [['x',5,95],['y',5,95],['size',30,250],['opacity',10,100],['duration',.5,4],['intensity',1,35]])if(!Number.isFinite(p.hero[key])||p.hero[key]<min||p.hero[key]>max)errors.push('Некорректные настройки героя: '+key);
if(!/^#[0-9a-f]{6}$/i.test(p.hero.color)||!['glow','blink','tint'].includes(p.hero.effect))errors.push('Некорректный эффект героя.');
const ids=new Set();p.questions.forEach((q,i)=>{const name=`Задание ${i+1}`;if(!q||typeof q.id!=='string'||ids.has(q.id)){errors.push(name+': повторный или отсутствующий ID.');return;}ids.add(q.id);if(!Array.isArray(q.options)||!Array.isArray(q.answers)){errors.push(name+': повреждены варианты ответа.');return;}if(!types[q.type]||typeof q.text!=='string'||(!q.text.trim()&&!(q.type==='passage'&&((typeof q.passage==='string'&&q.passage.trim())||q.pdf?.pages?.length)))||typeof q.label!=='string'||(!q.label.trim()&&!q.labelMedia?.image)||typeof q.stamp!=='string')errors.push(name+': заполните текст и подпись.');if(q.type==='text'){if(!Array.isArray(q.answers)||!q.answers.length||q.answers.some(a=>typeof a!=='string'||!a.trim()))errors.push(name+': введите эталон ответа.');}else if(q.type!=='passage'&&!(q.type==='audio'&&q.answerRequired===false)){if(!Array.isArray(q.options)||q.options.length<2||q.options.length>8||q.options.some(o=>!o||typeof o.text!=='string'||(!o.text.trim()&&!o.media?.image&&!o.media?.audio)||typeof o.id!=='string')||new Set(q.options.map(o=>o.id)).size!==q.options.length)errors.push(name+': нужны 2–8 заполненных вариантов с уникальными ID.');else if((q.type==='single'||q.type==='audio')&&q.options.filter(o=>o.correct).length!==1||q.type==='multiple'&&!q.options.some(o=>o.correct))errors.push(name+': укажите правильные ответы.');}});
const tids=new Set();p.tickets.forEach((t,i)=>{if(!t||typeof t.id!=='string'||tids.has(t.id)){errors.push('Повторный ID билета.');return;}tids.add(t.id);if(typeof t.name!=='string'||!['classic','learning'].includes(t.template))errors.push('Повреждены настройки билета.');if(!Number.isInteger(t.rows)||t.rows<2||t.rows>5||!Number.isInteger(t.cols)||t.cols<2||t.cols>9||!Array.isArray(t.cells)||t.cells.length!==t.rows*t.cols){errors.push(`Билет ${i+1}: неверная сетка.`);return;}if(!t.cells.some(Boolean))errors.push(`Билет ${i+1}: нет заданий.`);if(t.cells.some(id=>id!==null&&!ids.has(id)))errors.push(`Билет ${i+1}: потеряна связь с заданием.`);if(t.template==='classic'&&(t.rows!==3||t.cols!==9||[0,1,2].some(r=>t.cells.slice(r*9,r*9+9).filter(Boolean).length!==5)))errors.push(`Билет ${i+1}: в классическом билете нужно по 5 заданий в строке.`);});
if(!Number.isInteger(p.rules.lives)||p.rules.lives<1||p.rules.lives>10||!Number.isInteger(p.rules.min)||!Number.isInteger(p.rules.max)||p.rules.min<1||p.rules.max>6||p.rules.min>p.rules.max||p.rules.max>p.tickets.length)errors.push('Проверьте число жизней и диапазон билетов.');
for(const src of [p.design.background,p.hero.image,p.design.barrelImage,...p.questions.flatMap(q=>[q?.labelMedia?.image,q?.media?.image,...(Array.isArray(q?.options)?q.options:[]).map(o=>o?.media?.image)])])if(src&&(typeof src!=='string'||!/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(src)||src.length>14*1024*1024))errors.push('Некорректный или слишком большой ресурс.');
for(const k of ['table','accent','ticket','ink','cell','barrel','selected','correct','wrong','button','buttonText','modal'])if(!/^#[0-9a-f]{6}$/i.test(p.design[k]))errors.push('Некорректный цвет: '+k);
for(const q of p.questions){if(!q)continue;if(q.passage!==undefined&&typeof q.passage!=='string')errors.push('Некорректный текст для чтения.');if(q.pdf!==undefined&&q.pdf!==null&&(!q.pdf||typeof q.pdf.name!=='string'||typeof q.pdf.id!=='string'||!Array.isArray(q.pdf.pages)||!q.pdf.pages.length||q.pdf.pages.length>30||q.pdf.pages.some(x=>typeof x!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(x)||x.length>14*1024*1024)))errors.push('Некорректные страницы PDF.');if(q.showDetails!==undefined&&typeof q.showDetails!=='boolean')errors.push('Некорректный режим полной формулировки.');if(q.answerRequired!==undefined&&typeof q.answerRequired!=='boolean')errors.push('Некорректный режим аудиозадания.');if(q.type==='audio'&&!q.media?.audio)errors.push('Аудиозадание: загрузите запись.');for(const a of [q.media?.audio,...(Array.isArray(q.options)?q.options:[]).map(o=>o?.media?.audio)])if(a&&(typeof a!=='string'||!/^data:audio\/(mpeg|wav|ogg|mp4|webm);base64,[A-Za-z0-9+/=]+$/.test(a)||a.length>21*1024*1024))errors.push('Некорректная аудиозапись.');}
for(const k of ['questionColor','answerColor'])if(p.design[k]!==undefined&&!/^#[0-9a-f]{6}$/i.test(p.design[k]))errors.push('Некорректный цвет текста.');
if(!['Nunito','Roboto','Open Sans','Arial','Verdana','Georgia','Trebuchet MS','Tahoma','Times New Roman','Courier New','Palatino','Garamond','Helvetica','Impact','Comic Sans MS'].includes(p.design.font))errors.push('Неподдерживаемый шрифт.');for(const key of ['language','editorLanguage'])if(p[key]&&!['ru','en','uk','kk'].includes(p[key]))errors.push('Неподдерживаемый язык.');
for(const [key,min,max] of [['barrelSize',48,120],['titleSize',24,80],['instructionSize',12,36],['chooseSize',12,36],['questionSize',12,48],['answerSize',12,48],['tableOpacity',0,100]])if(p.design[key]!==undefined&&(!Number.isFinite(p.design[key])||p.design[key]<min||p.design[key]>max))errors.push('Некорректный параметр: '+key);
if(p.design.answerAnimation!==undefined&&!['none','fade','rise','zoom'].includes(p.design.answerAnimation))errors.push('Некорректная анимация.');if(p.design.animationDuration!==undefined&&(!Number.isFinite(p.design.animationDuration)||p.design.animationDuration<100||p.design.animationDuration>1500))errors.push('Некорректная длительность анимации.');
for(const key of ['nameSize','lineSize'])if(p.hero[key]!==undefined&&(!Number.isFinite(p.hero[key])||p.hero[key]<10||p.hero[key]>36))errors.push('Некорректный размер текста героя.');
if(p.hero.lines!==undefined&&(!p.hero.lines||typeof p.hero.lines!=='object'||Array.isArray(p.hero.lines)||Object.entries(p.hero.lines).some(([key,value])=>!['hello','thinking','cheer','encourage','won','lost'].includes(key)||typeof value!=='string')))errors.push('Некорректные реплики героя.');
if(p.hero.placement&&!['both','start','game'].includes(p.hero.placement))errors.push('Некорректное размещение героя.');return errors;}
function assignCell(p,ticketId,index,id){const t=p.tickets.find(t=>t.id===ticketId);if(!t||!Number.isInteger(index)||index<0||index>=t.cells.length||id!==null&&!p.questions.some(q=>q.id===id))return false;t.cells[index]=id;if(t.template==='classic'&&[0,1,2].some(r=>t.cells.slice(r*9,r*9+9).filter(Boolean).length!==5))t.template='learning';return true;}
function moveCell(p,from,to){const a=p.tickets.find(t=>t.id===from.ticketId),b=p.tickets.find(t=>t.id===to.ticketId);if(!a||!b||!Number.isInteger(from.index)||!Number.isInteger(to.index)||from.index<0||to.index<0||from.index>=a.cells.length||to.index>=b.cells.length||a.cells[from.index]===b.cells[to.index])return false;[a.cells[from.index],b.cells[to.index]]=[b.cells[to.index],a.cells[from.index]];for(const t of new Set([a,b]))if(t.template==='classic'&&[0,1,2].some(r=>t.cells.slice(r*9,r*9+9).filter(Boolean).length!==5))t.template='learning';return true;}
class Session{constructor(p,count){this.p=p;this.tickets=shuffle(p.tickets).slice(0,count);this.lives=p.rules.lives;this.errors=0;this.done=new Set();this.drafts={};this.rejected={};this.orders={};this.total=this.tickets.reduce((s,t)=>s+t.cells.filter(Boolean).length,0);this.status='playing';}
complete(key,q){if(this.status!=='playing'||this.done.has(key)||!(q.type==='passage'||q.type==='audio'&&q.answerRequired===false))return 'blocked';this.done.add(key);if(this.done.size===this.total)this.status='win';return 'complete';}
check(key,q,answer){if(q.type==='passage'||q.type==='audio'&&q.answerRequired===false)return 'blocked';if(this.status!=='playing'||this.done.has(key))return 'blocked';if(answer==null||typeof answer==='string'&&!answer.trim()||Array.isArray(answer)&&!answer.length)return 'empty';const signature=JSON.stringify(answer);if(this.rejected[key]===signature)return 'blocked';if(correct(q,answer)){this.done.add(key);if(this.done.size===this.total)this.status='win';return 'correct';}this.rejected[key]=signature;this.errors++;this.lives--;if(!this.lives)this.status='lose';return 'wrong';}}
return {clone,uid,esc,shuffle,types,question,demo,normalize,correct,validate,assignCell,moveCell,Session};
})();
