let pendingMedia=null;
function mediaControls(owner,key,{imageOnly=false}={}){const media=owner.media||{};return `<div class="media-controls" data-user>${media.image?`<img class="media-thumb" src="${E(media.image)}" alt="Изображение"><button class="remove-media" data-media-remove="${E(key+':image')}" aria-label="Удалить изображение">×</button>`:''}${!imageOnly&&media.audio?`<audio controls preload="metadata" src="${E(media.audio)}"></audio><button class="small-button" data-media-remove="${E(key+':audio')}">Удалить аудио</button>`:''}<div class="media-upload-buttons"><button class="small-button" data-media-upload="${E(key+':image')}">▧ Картинка / GIF</button>${imageOnly?'':`<button class="small-button" data-media-upload="${E(key+':audio')}">♫ Аудиозапись</button>`}</div></div>`;}
function mediaOwner(key){const [kind,qid,oid]=key.split(':');const q=project.questions.find(q=>q.id===qid);return kind==='l'?(q?{media:q.labelMedia}:null):kind==='q'?q:q?.options.find(o=>o.id===oid);}
function bindMediaControls(container){container.querySelectorAll('[data-media-upload]').forEach(b=>b.onclick=()=>{const key=b.dataset.mediaUpload,kind=key.split(':').pop();pendingMedia={key,kind};const f=$('#media-file');f.accept=kind==='image'?'image/png,image/jpeg,image/webp,image/gif':'audio/mpeg,audio/wav,audio/ogg,audio/mp4,audio/webm';f.click();});container.querySelectorAll('[data-media-remove]').forEach(b=>b.onclick=()=>{const key=b.dataset.mediaRemove,kind=key.split(':').pop(),owner=mediaOwner(key);if(!owner)return;change(()=>(owner.media??={})[kind]='','',true);renderSettings();});}
function confirmDeletion(title,text,onDelete){modal(title,`<p>${E(text)}</p><div class="dialog-actions"><button id="keep-item">Оставить</button><button id="remove-item" class="danger">Удалить</button></div>`);$('#keep-item').onclick=()=>$('#dialog').close();$('#remove-item').onclick=()=>{$('#dialog').close();onDelete();};}
function deleteTicket(id){const ticket=project.tickets.find(t=>t.id===id);if(!ticket)return;confirmDeletion('Удалить билет?',`«${ticket.name}» будет удалён. Задания останутся в банке.`,()=>{change(()=>{project.tickets=project.tickets.filter(t=>t.id!==id);project.rules.max=Math.max(1,Math.min(project.rules.max,project.tickets.length));project.rules.min=Math.min(project.rules.min,project.rules.max);if(cellContext?.ticketId===id)cellContext=null;if(selectedTicket===id){selectedTicket=project.tickets[0]?.id;selectedCell=0;}},'',true);renderSettings();});}
function mountMediaUploads(){
  $('#media-file').onchange=async event=>{const file=event.target.files[0],target=pendingMedia;event.target.value='';if(!file||!target)return;try{toast(target.kind==='image'?'Сжимаю изображение…':'Загружаю аудиозапись…');const result=await LotoMedia.prepare(file,{max:target.key.startsWith('l:')?320:target.key.startsWith('o:')?480:960,onProgress:(n,total)=>status(`Сжатие GIF: ${n} / ${total}`)});if(!result.mime.startsWith(target.kind==='image'?'image/':'audio/'))throw Error('Выбран файл другого типа.');const owner=mediaOwner(target.key);if(!owner)return toast('Задание уже удалено.');change(()=>{owner.media??={image:'',audio:''};owner.media[target.kind]=result.data;},'',true);renderSettings();toast(target.kind==='image'?`Изображение готово: ${(result.before/1024).toFixed(0)} → ${(result.after/1024).toFixed(0)} КБ`:'Аудиозапись добавлена.');}catch(error){toast(error.message);}};
  $('#image-file').onchange=async event=>{const file=event.target.files[0],target=imageTarget;event.target.value='';if(!file)return;try{toast('Сжимаю изображение…');const result=await LotoMedia.prepare(file,{max:target==='background'?1600:target==='barrel'?320:640,onProgress:(n,total)=>status(`Сжатие GIF: ${n} / ${total}`)});if(!result.mime.startsWith('image/'))throw Error('Выберите изображение.');change(()=>{if(target==='hero')project.hero.image=result.data;else if(target==='barrel')project.design.barrelImage=result.data;else project.design.background=result.data;});renderSettings();toast(`Изображение готово: ${(result.before/1024).toFixed(0)} → ${(result.after/1024).toFixed(0)} КБ`);}catch(error){toast(error.message);}};
}
