let pendingMedia=null;
function mediaControls(owner,key,{imageOnly=false}={}){const media=owner.media||{};return `<div class="media-controls" data-user>${media.image?`<img class="media-thumb" src="${E(media.image)}" alt="Изображение"><button class="remove-media" data-media-remove="${E(key+':image')}" aria-label="Удалить изображение">×</button>`:''}${!imageOnly&&media.audio?`<audio controls preload="metadata" src="${E(media.audio)}"></audio><button class="small-button" data-media-remove="${E(key+':audio')}">Удалить аудио</button>`:''}<div class="media-upload-buttons"><button class="small-button" data-media-upload="${E(key+':image')}">▧ Картинка / GIF</button><button class="small-button" data-gif-library="${E(key)}">Библиотека GIF</button>${imageOnly?'':`<button class="small-button" data-media-upload="${E(key+':audio')}">♫ Аудиозапись</button>`}</div></div>`;}
function mediaOwner(key){const [kind,qid,oid]=key.split(':');const q=project.questions.find(q=>q.id===qid);return kind==='l'?(q?{media:q.labelMedia}:null):kind==='q'?q:q?.options.find(o=>o.id===oid);}
function bindMediaControls(container){container.querySelectorAll('[data-gif-library]').forEach(b=>b.onclick=()=>openGifLibrary(b.dataset.gifLibrary));container.querySelectorAll('[data-media-upload]').forEach(b=>b.onclick=()=>{const key=b.dataset.mediaUpload,kind=key.split(':').pop();pendingMedia={key,kind};const f=$('#media-file');f.accept=kind==='image'?'image/png,image/jpeg,image/webp,image/gif':'audio/mpeg,audio/wav,audio/ogg,audio/mp4,audio/webm';f.click();});container.querySelectorAll('[data-media-remove]').forEach(b=>b.onclick=()=>{const key=b.dataset.mediaRemove,kind=key.split(':').pop(),owner=mediaOwner(key);if(!owner)return;change(()=>(owner.media??={})[kind]='','',true);renderSettings();});}
function confirmDeletion(title,text,onDelete){modal(title,`<p>${E(text)}</p><div class="dialog-actions"><button id="keep-item">Оставить</button><button id="remove-item" class="danger">Удалить</button></div>`);$('#keep-item').onclick=()=>$('#dialog').close();$('#remove-item').onclick=()=>{$('#dialog').close();onDelete();};}
function deleteTicket(id){const ticket=project.tickets.find(t=>t.id===id);if(!ticket)return;confirmDeletion('Удалить билет?',`«${ticket.name}» будет удалён. Задания останутся в банке.`,()=>{change(()=>{project.tickets=project.tickets.filter(t=>t.id!==id);project.rules.max=Math.max(1,Math.min(project.rules.max,project.tickets.length));project.rules.min=Math.min(project.rules.min,project.rules.max);if(cellContext?.ticketId===id)cellContext=null;if(selectedTicket===id){selectedTicket=project.tickets[0]?.id;selectedCell=0;}},'',true);renderSettings();});}
function mountMediaUploads(){
  $('#media-file').onchange=async event=>{const file=event.target.files[0],target=pendingMedia;event.target.value='';if(!file||!target)return;try{toast(target.kind==='image'?'Сжимаю изображение…':'Загружаю аудиозапись…');const result=await LotoMedia.prepare(file,{max:target.key.startsWith('l:')?320:target.key.startsWith('o:')?480:960,onProgress:(n,total)=>status(`Сжатие GIF: ${n} / ${total}`)});if(!result.mime.startsWith(target.kind==='image'?'image/':'audio/'))throw Error('Выбран файл другого типа.');const owner=mediaOwner(target.key);if(!owner)return toast('Задание уже удалено.');change(()=>{owner.media??={image:'',audio:''};owner.media[target.kind]=result.data;},'',true);renderSettings();toast(target.kind==='image'?`Изображение готово: ${(result.before/1024).toFixed(0)} → ${(result.after/1024).toFixed(0)} КБ`:'Аудиозапись добавлена.');}catch(error){toast(error.message);}};
  $('#image-file').onchange=async event=>{const file=event.target.files[0],target=imageTarget;event.target.value='';if(!file)return;try{toast('Сжимаю изображение…');const result=await LotoMedia.prepare(file,{max:target==='background'?1600:target==='barrel'?320:640,onProgress:(n,total)=>status(`Сжатие GIF: ${n} / ${total}`)});if(!result.mime.startsWith('image/'))throw Error('Выберите изображение.');change(()=>{if(target==='hero')project.hero.image=result.data;else if(target==='barrel')project.design.barrelImage=result.data;else project.design.background=result.data;});renderSettings();toast(`Изображение готово: ${(result.before/1024).toFixed(0)} → ${(result.after/1024).toFixed(0)} КБ`);}catch(error){toast(error.message);}};
}


function projectGifs(){const seen=new Set(),images=[];for(const data of [project.hero.image,...project.questions.flatMap(q=>[q.labelMedia?.image,q.media?.image,...q.options.map(o=>o.media?.image)])])if(data?.startsWith('data:image/gif;')&&!seen.has(data)){seen.add(data);images.push({name:'GIF из проекта '+(images.length+1),data});}return images;}
function applyLibraryGif(target,data,noto=false){const owner=target==='hero'?null:mediaOwner(target);if(target!=='hero'&&!owner)throw Error('Задание уже удалено.');change(()=>{if(target==='hero')project.hero.image=data;else(owner.media??={}).image=data;if(noto)project.notoAttribution=true;},'',true);$('#dialog').close();renderSettings();}
async function fetchNotoGif(item){if(!NotoGifCatalog.some(x=>x.code===item.code))throw Error('Анимация не найдена в каталоге.');const controller=typeof AbortController==='function'?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),30000):null;try{const response=await fetch('https://fonts.gstatic.com/s/e/notoemoji/latest/'+item.code+'/512.gif',{signal:controller?.signal,credentials:'omit'});if(!response.ok)throw Error('Сервис Noto временно недоступен. Попробуйте ещё раз.');const blob=await response.blob();return await LotoMedia.prepare(blob,{max:320});}finally{if(timer)clearTimeout(timer);}}
function openGifLibrary(target){
 const local=projectGifs(),baseProject=project;let page=0,busy=false;
 modal('Библиотека GIF · Noto',`<p>${NotoGifCatalog.length} анимация Noto от Google. Для просмотра и загрузки нужен интернет. Выбранный GIF сжимается и сохраняется внутри проекта.</p><div class="row"><label class="field"><span>Поиск</span><input id="gif-search" placeholder="cat, кот или 🐈"></label><label class="field"><span>Раздел</span><select id="gif-category"><option value="">Все анимации Noto</option>${[...new Set(NotoGifCatalog.map(x=>x.category))].map(c=>`<option>${E(c)}</option>`).join('')}<option value="project">GIF из проекта</option></select></label></div><p id="gif-status" role="status"></p><div class="gif-library" id="gif-results"></div><div class="dialog-actions"><button id="gif-prev">← Назад</button><span id="gif-page"></span><button id="gif-next">Далее →</button></div><p class="note">Noto Animated Emoji © Google · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>. При загрузке изменяется размер. <a href="https://googlefonts.github.io/noto-emoji-animation/" target="_blank" rel="noopener">Оригинальная библиотека</a></p>`);
 const aliases={'кот':'cat','кошка':'cat','собака':'dog','собачка':'dog','сердце':'heart','улыбка':'smile','звезда':'star','огонь':'fire','робот':'robot','медведь':'bear','цветок':'flower','солнце':'sun','луна':'moon','сова':'owl','птица':'bird','рука':'hand','книга':'book','школа':'school','карандаш':'pencil'};
 const render=()=>{const raw=$('#gif-search').value.toLowerCase().trim(),term=aliases[raw]||raw,category=$('#gif-category').value,items=category==='project'?local:NotoGifCatalog.filter(x=>(!category||x.category===category)&&(!term||(x.name+' '+x.emoji+' '+x.category).toLowerCase().includes(term)));page=Math.max(0,Math.min(page,Math.ceil(items.length/24)-1));const slice=items.slice(page*24,page*24+24);$('#gif-results').innerHTML=slice.length?slice.map((x,i)=>`<button data-gif-pick="${i}" ${busy?'disabled':''}><img loading="lazy" src="${E(x.data||'https://fonts.gstatic.com/s/e/notoemoji/latest/'+x.code+'/512.webp')}" alt="${E(x.emoji||'GIF')}"><span>${E(x.name)}</span></button>`).join(''):'<p>Анимации не найдены. Попробуйте другой запрос или загрузите свой GIF.</p>';$('#gif-page').textContent=(page+1)+' / '+Math.max(1,Math.ceil(items.length/24));$('#gif-prev').disabled=busy||page===0;$('#gif-next').disabled=busy||(page+1)*24>=items.length;$('#gif-results').querySelectorAll('[data-gif-pick]').forEach(b=>b.onclick=async()=>{if(busy)return;const item=slice[Number(b.dataset.gifPick)];busy=true;$('#gif-status').textContent='Загружаю и сжимаю GIF…';render();try{const result=item.data?{data:item.data}:await fetchNotoGif(item);if(project!==baseProject)throw Error('Проект изменился. Откройте библиотеку заново.');applyLibraryGif(target,result.data,!item.data);}catch(e){busy=false;if($('#gif-status')){$('#gif-status').textContent='Не удалось загрузить GIF. '+(e.name==='AbortError'?'Проверьте интернет и повторите.':e.message);render();}}});};
 $('#gif-search').oninput=()=>{page=0;render();};$('#gif-category').onchange=()=>{page=0;render();};$('#gif-prev').onclick=()=>{page--;render();};$('#gif-next').onclick=()=>{page++;render();};render();
}
