function updateMathPreview(input){if(!input?.matches('textarea'))return;const relevant=/questions\.\d+\.(text|passage)$/.test(input.dataset.path||'');if(!relevant)return;let view=input.nextElementSibling;if(!view?.classList.contains('field-math-preview')){view=document.createElement('div');view.className='field-math-preview';view.setAttribute('data-user','');input.after(view);}view.hidden=!input.value.includes('$');view.innerHTML=LotoUI.math(input.value);}

function insertMath(value){let input=lastMathInput;if(!input?.isConnected||!/questions\.\d+\.(text|passage)$/.test(input.dataset.path||''))input=document.querySelector('textarea[data-path$=".text"]');if(!input)return toast('Выберите поле задания.');const start=input.selectionStart??input.value.length,end=input.selectionEnd??start;input.setRangeText(value,start,end,'end');input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));}
function showMathHelp(){const templates=[['Дробь',String.raw`$\frac{x+1}{y-2}$`],['Степени и индексы','$x^{10}+a_{n+1}$'],['Корень',String.raw`$\sqrt[n]{a}$`],['Скобки',String.raw`$\left(\frac{a}{b}\right)$`],['Модуль',String.raw`$\left|x\right|$`],['Знаки',String.raw`$\times\;\cdot\;\div\;\pm\;\neq\;\leq\;\geq\;\infty\;\pi\;\approx$`],['Сумма',String.raw`$\sum_{i=1}^{n} i$`],['Предел',String.raw`$\lim_{x \to 0} f(x)$`],['Проценты',String.raw`$25\%$`],['Геометрия',String.raw`$\angle ABC=90^\circ,\quad a\parallel b,\quad a\perp b,\quad\overline{AB}$`],['Единицы',String.raw`$S=24\text{ см}^2$`],['Квадратное уравнение',String.raw`$$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$`],['Система',String.raw`$$\begin{cases} x+y=5 \\ x-y=1 \end{cases}$$`]];modal('Математическая запись — LaTeX','<p>Вставьте шаблон в выбранное поле и замените значения. Эталон текстового ответа сравнивается как текст; выражения автоматически не вычисляются.</p><div class="math-template-list">'+templates.map(([name,code],i)=>`<button data-template="${i}"><strong>${E(name)}</strong><div data-user>${LotoUI.math(code)}</div><code data-user>${E(code)}</code></button>`).join('')+'</div>');document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{$('#dialog').close();insertMath(templates[Number(b.dataset.template)][1]);});}
async function copyEmbedText(field){
  const text=field.value;if(!text)return false;
  // Legacy path runs synchronously inside the click and works for local HTML files.
  field.focus();field.select();field.setSelectionRange(0,text.length);
  try{if(document.execCommand('copy'))return true;}catch{}
  try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true;}}catch{}
  field.focus();field.select();return false;
}
async function optimizeProject(original,max,quality){const copy=Loto.clone(original);const media=copy.questions.flatMap(q=>[q.media,...q.options.map(o=>o.media)]).filter(Boolean);for(const [obj,key] of [[copy.design,'background'],[copy.hero,'image'],[copy.design,'barrelImage'],...media.map(m=>[m,'image'])]){if(!obj[key]||obj[key].startsWith('data:image/gif'))continue;const img=await decodeImage(obj[key]),ratio=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));if(blob){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Не удалось сжать изображение.'));r.readAsDataURL(blob);});if(data.length<obj[key].length)obj[key]=data;}}
  const used=new Set(copy.tickets.flatMap(t=>t.cells).filter(Boolean));copy.questions=copy.questions.filter(q=>used.has(q.id));return copy;}
let embedPreferences={mode:'inline',url:'',width:960,height:720,responsive:true};
function openEmbed(optimizeFirst=false){
  if(Loto.validate(project).length)return validationDialog();
  const sourceProject=Loto.clone(project),normalHTML=makeHTML(sourceProject);let currentHTML=normalHTML,optimized=false;
  modal('Код для Genially',`<p>Подготовьте код игры, проверьте его и скопируйте в Genially.</p><label class="field"><span>Способ вставки</span><select id="embed-mode"><option value="inline" ${embedPreferences.mode==='inline'?'selected':''}>Игра целиком — код без ссылки</option><option value="url" ${embedPreferences.mode==='url'?'selected':''}>Ссылка на опубликованную игру (HTTPS)</option></select></label><label class="field" id="url-field"><span>HTTPS-адрес опубликованной игры</span><input id="publish-url" type="url" value="${E(embedPreferences.url)}" placeholder="https://example.com/loto.html"></label><div class="row"><label class="field"><span>Ширина, px</span><input id="embed-width" type="number" value="${embedPreferences.width}" min="360" max="2400"></label><label class="field"><span>Высота, px</span><input id="embed-height" type="number" value="${embedPreferences.height}" min="360" max="2400"></label></div><label class="checkbox"><input id="embed-responsive" type="checkbox" ${embedPreferences.responsive?'checked':''}>Адаптивная ширина</label><details id="embed-opt-settings" ${optimizeFirst?'open':''}><summary>Облегчить код для Genially</summary><label class="field"><span>Максимальная сторона изображения</span><select id="opt-size"><option value="1920">1920 px</option><option value="1280" selected>1280 px</option><option value="960">960 px</option></select></label><label class="field"><span>Качество изображений, %</span><input id="opt-quality" type="range" min="50" max="100" value="85"></label><p>Уменьшим изображения и сожмём встроенную игру. Ваш проект не изменится.</p><button id="run-opt" class="small-button wide">Облегчить код</button></details><div id="embed-size" class="note"></div><label class="field"><span>Код для вставки</span><textarea id="embed-code" readonly rows="5" spellcheck="false"></textarea></label><p id="embed-error" role="status"></p><div class="row"><button class="small-button primary" id="copy-embed">Копировать код</button><button class="small-button" id="check-embed">Проверить код</button></div><div class="row"><button class="small-button wide" id="download-embed">Скачать код .txt</button><button class="small-button wide" id="download-embed-html">Скачать игру HTML</button></div><div id="embed-test"></div><p id="embed-compatibility"></p>`);
  const generate=()=>{embedPreferences={mode:$('#embed-mode').value,url:$('#publish-url').value,width:Number($('#embed-width').value),height:Number($('#embed-height').value),responsive:$('#embed-responsive').checked};$('#url-field').hidden=embedPreferences.mode!=='url';$('#embed-test').replaceChildren();try{const code=LotoUI.embedCode({...embedPreferences,html:currentHTML});$('#embed-code').value=code;$('#copy-embed').disabled=false;$('#check-embed').disabled=false;$('#download-embed').disabled=false;const before=new Blob([LotoUI.embedCode({...embedPreferences,html:normalHTML})]).size,after=new Blob([code]).size;$('#embed-size').textContent=`Код: ${(after/1024).toFixed(1)} КБ`+(optimized?` · до: ${(before/1024).toFixed(1)} КБ · уменьшение: ${Math.max(0,(1-after/before)*100).toFixed(1)}%`:'');$('#embed-error').textContent=optimized?'Облегчённый код готов к копированию.':'Код готов к копированию.';}catch(err){$('#embed-code').value='';$('#copy-embed').disabled=true;$('#check-embed').disabled=true;$('#download-embed').disabled=true;$('#embed-error').textContent=err.message;}
    $('#embed-compatibility').textContent=embedPreferences.mode==='inline'?'Встроенный код использует iframe srcdoc. Если Genially удаляет его при сохранении, используйте режим HTTPS-ссылки. Окончательную проверку выполните в опубликованном Genially.':'Разместите скачанную HTML-игру по указанному HTTPS-адресу. Хостинг должен разрешать iframe. Оптимизация уменьшает саму игру; длина iframe-ссылки почти не меняется.';};
  ['embed-mode','publish-url','embed-width','embed-height','embed-responsive'].forEach(id=>$('#'+id).oninput=generate);
  $('#copy-embed').onclick=async()=>{const ok=await copyEmbedText($('#embed-code'));$('#embed-error').textContent=ok?'Код скопирован. Вставьте его в Genially.':'Браузер запретил автоматическое копирование. Код выделен: нажмите Ctrl+C или Cmd+C, либо скачайте .txt.';if(ok)toast('Код для Genially скопирован.');};
  $('#check-embed').onclick=()=>{$('#embed-test').innerHTML=$('#embed-code').value;};
  $('#download-embed').onclick=()=>download('Код для Genially.txt',$('#embed-code').value,'text/plain');
  $('#download-embed-html').onclick=()=>download(optimized?'Лото — облегчённая.html':'Лото.html',currentHTML,'text/html');
  $('#run-opt').onclick=async()=>{const b=$('#run-opt');b.disabled=true;b.textContent='Оптимизация…';try{const copy=await optimizeProject(sourceProject,Number($('#opt-size').value),Number($('#opt-quality').value)/100);const packed=await packHTML(makeHTML(copy));currentHTML=packed.html;optimized=true;generate();if(!packed.compressed)$('#embed-error').textContent='Изображения оптимизированы. Сжатие кода недоступно или не уменьшает размер.';}catch(err){$('#embed-error').textContent='Ошибка оптимизации: '+err.message;}finally{b.disabled=false;b.textContent='Облегчить код';}};
  generate();
}
