class LotoGame {
constructor(root,project,{edit=false,onSelect=()=>{},onHeroMove=()=>{},onScreen=()=>{}}={}){this.root=root;this.p=project;this.edit=edit;this.onSelect=onSelect;this.onHeroMove=onHeroMove;this.onScreen=onScreen;this.screen='start';this.session=null;this.active=null;this.render();}
setProject(p,structural=false){this.p=p;if(structural){this.session=null;this.active=null;this.screen='start';this.render();return;}if(this.session)this.session.p=p;this.style();this.root.querySelectorAll('[data-title]').forEach(e=>e.textContent=p.title);this.root.querySelectorAll('[data-description]').forEach(e=>e.textContent=p.description);this.root.querySelectorAll('[data-q-label]').forEach(e=>{const q=p.questions.find(q=>q.id===e.dataset.qLabel);if(q)e.textContent=q.label;});this.updateHero();}
style(){const d=this.p.design;this.root.classList.add('game');for(const k of ['table','accent','ticket','ink','cell','barrel','selected','correct','wrong','button','buttonText','modal'])this.root.style.setProperty('--'+k,d[k]);this.root.style.setProperty('--radius',d.radius+'px');this.root.style.setProperty('--game-font',d.font);this.root.style.setProperty('--game-size',d.fontSize+'px');const bg=this.root.querySelector('.game-background');if(bg){bg.style.backgroundImage=d.background?`linear-gradient(#000${Math.round(d.dim*2.55).toString(16).padStart(2,'0')},#000${Math.round(d.dim*2.55).toString(16).padStart(2,'0')}),url("${d.background}")`:'';bg.style.backgroundSize=d.fit==='repeat'?'auto':d.fit;bg.style.backgroundRepeat=d.fit==='repeat'?'repeat':'no-repeat';bg.style.backgroundPosition=d.position;}}
updateHero(){const h=this.p.hero,e=this.root.querySelector('.hero');if(!e)return;e.hidden=!h.show||!h.image;e.src=h.image||'';e.style.left=h.x+'%';e.style.top=h.y+'%';e.style.width=h.size+'px';e.style.opacity=h.opacity/100;e.style.transform=`translate(-50%,-50%) scaleX(${h.flip?-1:1})`;e.style.setProperty('--hero-color',h.color);e.style.setProperty('--hero-duration',h.duration+'s');e.style.setProperty('--hero-intensity',h.intensity+'px');e.onpointerdown=ev=>{if(!this.edit)return;ev.preventDefault();e.setPointerCapture(ev.pointerId);const rect=this.root.getBoundingClientRect();let next=null;const move=event=>{next={x:Math.max(5,Math.min(95,(event.clientX-rect.left)/rect.width*100)),y:Math.max(5,Math.min(95,(event.clientY-rect.top)/rect.height*100))};e.style.left=next.x+'%';e.style.top=next.y+'%';};e.onpointermove=move;e.onpointerup=()=>{e.onpointermove=null;e.onpointerup=null;if(next)this.onHeroMove(next);};e.onpointercancel=()=>{e.onpointermove=null;this.updateHero();};};e.onpointerenter=()=>this.heroEffect('hover');e.onclick=()=>{this.heroEffect('hover');if(this.edit)this.onSelect('Герой');};}
heroEffect(event){const h=this.p.hero,e=this.root.querySelector('.hero');if(!e||!h[event])return;e.classList.remove('glow','blink','tint');void e.offsetWidth;e.classList.add(h.effect);clearTimeout(this.effectTimer);this.effectTimer=setTimeout(()=>e.classList.remove('glow','blink','tint'),h.duration*1000);}
start(count){const errors=Loto.validate(this.p);if(errors.length){this.message(errors[0]);return;}this.session=new Loto.Session(this.p,Number(count));this.screen='game';this.active=null;this.render();}
show(screen){this.screen=screen;this.active=null;if(['game','question','win','lose'].includes(screen)&&!this.session)this.session=new Loto.Session(this.p,this.p.rules.min);if(screen==='question'){const t=this.session.tickets[0],i=t.cells.findIndex(Boolean);this.active={key:t.id+':'+i,id:t.cells[i]};}this.render();}
message(s){const e=this.root.querySelector('.game-message');if(e)e.textContent=s;}
restart(home=false){if(this.session?.status==='playing'&&(this.session.done.size||this.session.errors)&&!confirm('Завершить текущую игру? Прогресс будет сброшен.'))return;this.session=null;this.active=null;this.screen=home?'start':'game';if(home)this.render();else this.start(this.p.rules.min);}
render(){this.onScreen(this.active?'question':this.screen);const {esc}=Loto,p=this.p,s=this.session;this.root.innerHTML='<div class="game-background"></div><div class="table-stitch"></div><img class="hero" alt="Герой игры"><div class="game-content"></div>';const c=this.root.querySelector('.game-content');
if(this.screen==='start'){c.innerHTML=`<div class="start-screen"><span class="game-eyebrow">УЧИСЬ · ИГРАЙ · ПОБЕЖДАЙ</span><div class="barrel-illustration" aria-hidden="true"><i class="wood small">7</i><i class="wood large">42</i><i class="wood small">15</i></div><span class="game-kicker">УЧЕБНОЕ ЛОТО</span><h1 data-title>${esc(p.title)}</h1><p data-description>${esc(p.description)}</p><div class="start-divider"></div><label for="ticket-count">Сколько билетов возьмём?</label><div class="count-choices" role="group" aria-label="Количество билетов">${Array.from({length:Math.max(0,Math.min(p.rules.max,p.tickets.length)-p.rules.min+1)},(_,i)=>i+p.rules.min).map((n,i)=>`<button class="count-choice ${i===0?'chosen':''}" data-count="${n}" aria-pressed="${i===0}">${n}<small>${n===1?'билет':n<5?'билета':'билетов'}</small></button>`).join('')}</div><button class="gold-button start-play">${esc(p.screens.startButton)} <span>→</span></button><div class="game-instruction"><span>♡ ${p.rules.lives} жизни</span><span>✦ В своём темпе</span></div><p class="game-message" role="status"></p></div>`;let count=p.rules.min;c.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{count=Number(b.dataset.count);c.querySelectorAll('[data-count]').forEach(e=>{e.classList.toggle('chosen',e===b);e.setAttribute('aria-pressed',e===b);});});c.querySelector('.start-play').onclick=()=>this.start(count);
}else if(this.screen==='win'||this.screen==='lose'){const win=this.screen==='win';c.innerHTML=`<div class="end-screen"><span class="end-icon">${win?'🏆':'🌱'}</span><div class="game-kicker">${win?'ЛОТО СОБРАНО':'НОВАЯ ПОПЫТКА — НОВЫЙ ШАНС'}</div><h1>${esc(p.screens[win?'winTitle':'loseTitle'])}</h1><p>${esc(p.screens[win?'winText':'loseText'])}</p><div class="end-stats"><div><strong>${s?.done.size||0} / ${s?.total||0}</strong><span>Собрано бочонков</span></div><div><strong>${s?.errors||0}</strong><span>Ошибок</span></div></div><button class="gold-button again">${esc(p.screens.again)}</button><button class="text-button home">На главный экран</button></div>`;c.querySelector('.again').onclick=()=>this.restart();c.querySelector('.home').onclick=()=>this.restart(true);
}else{c.innerHTML=`<header class="game-header"><div><span class="game-kicker">УЧЕБНОЕ ЛОТО</span><h2 data-title>${esc(p.title)}</h2></div><div class="game-lives" aria-label="Жизни">${this.livesHTML()}</div></header><div class="game-progress"><span>Собрано бочонков <b>${s.done.size} / ${s.total}</b></span><button class="text-button home">↶ Начать заново</button></div><div class="progress-track"><i style="width:${s.done.size/s.total*100}%"></i></div><div class="answer-zone"></div><div class="tickets">${s.tickets.map(t=>`<section class="loto-ticket"><div class="ticket-heading"><span>✦ ${esc(t.name)}</span><span>${t.cells.filter((q,i)=>q&&s.done.has(t.id+':'+i)).length} / ${t.cells.filter(Boolean).length}</span></div><div class="ticket-grid" style="--cols:${t.cols}">${t.cells.map((id,i)=>{const q=p.questions.find(q=>q.id===id),key=t.id+':'+i,done=s.done.has(key);return q?`<button class="ticket-cell ${done?'closed':''} ${this.active?.key===key?'active':''}" data-cell="${esc(key)}" data-q="${esc(id)}" ${done?'disabled':''} title="${esc(q.text)}">${done?`<span class="mini-barrel">${esc(q.stamp)}</span>`:`<span data-q-label="${esc(id)}">${esc(q.label)}</span>`}</button>`:'<div class="ticket-cell empty" aria-hidden="true"><i>✦</i></div>';}).join('')}</div></section>`).join('')}</div><p class="game-message" role="status" aria-live="polite">Выберите задание на любом билете</p>`;c.querySelector('.home').onclick=()=>this.restart();c.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{if(this.edit){this.onSelect('Задания',b.dataset.q,b.dataset.cell);return;}if(s.status!=='playing')return;this.active={key:b.dataset.cell,id:b.dataset.q};this.render();});this.renderAnswer();}
this.style();this.updateHero();}
livesHTML(){const r=this.p.rules,s=this.session;if(r.lifeFormat==='count')return Loto.esc(r.emoji)+' × '+s.lives;return Array.from({length:r.lives},(_,i)=>`<span style="opacity:${i<s.lives?1:r.faded?.2:0}">${Loto.esc(r.emoji)}</span>`).join('');}
renderAnswer(){const z=this.root.querySelector('.answer-zone');if(!z)return;if(!this.active){z.innerHTML='<div class="barrel-rest"><i class="wood">?</i><div><strong>Каждый бочонок — новое открытие</strong><p>Нажмите на клетку и найдите правильный ответ</p></div></div>';return;}const {esc}=Loto,s=this.session,{key,id}=this.active,q=this.p.questions.find(q=>q.id===id);if(!q)return;const opts=q.options||[];if(!s.orders[key]){s.orders[key]=Loto.shuffle(opts.map(o=>o.id));if(q.type==='order'&&JSON.stringify(s.orders[key])===JSON.stringify(opts.map(o=>o.id)))s.orders[key].reverse();}if(!(key in s.drafts))s.drafts[key]=q.type==='order'?[...s.orders[key]]:q.type==='multiple'?[]:'';
const a=s.drafts[key];z.innerHTML=`<div class="question-panel"><div class="question-top"><span>${esc(Loto.types[q.type])}</span><button class="close-question" aria-label="Закрыть задание">×</button></div><h3>${esc(q.text)}</h3><div class="answer-inputs">${q.type==='text'?`<i class="wood neutral">?</i><input class="written-answer" aria-label="Ваш ответ" placeholder="Введите ответ…" value="${esc(a)}" autocomplete="off">`:(q.type==='order'?a:s.orders[key]).map((id,i)=>{const o=opts.find(o=>o.id===id);return q.type==='order'?`<div class="order-item" draggable="true" data-order="${i}"><i class="wood">${esc(o.text)}</i><span><button data-move="${i},-1" aria-label="Переместить ${esc(o.text)} влево" ${i===0?'disabled':''}>←</button><button data-move="${i},1" aria-label="Переместить ${esc(o.text)} вправо" ${i===a.length-1?'disabled':''}>→</button></span></div>`:`<button class="wood answer-barrel ${(q.type==='multiple'?a.includes(id):a===id)?'chosen':''}" data-answer="${esc(id)}" aria-pressed="${q.type==='multiple'?a.includes(id):a===id}">${esc(o.text)}</button>`;}).join('')}</div><div class="check-row"><span class="answer-feedback" role="status">${q.type==='multiple'?'Отметьте все подходящие варианты':q.type==='order'?'Перетащите бочонки или используйте стрелки':'Выберите или введите ответ'}</span><button class="gold-button check">${esc(this.p.design.checkLabel)}</button></div></div>`;
z.querySelector('.close-question').onclick=()=>{this.active=null;this.render();};const change=()=>{delete s.rejected[key];z.querySelector('.check').disabled=!this.ready(q,s.drafts[key]);};
z.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const v=b.dataset.answer;s.drafts[key]=q.type==='multiple'?(s.drafts[key].includes(v)?s.drafts[key].filter(x=>x!==v):[...s.drafts[key],v]):v;change();this.renderAnswer();});const input=z.querySelector('input');if(input)input.oninput=()=>{s.drafts[key]=input.value;change();};
const move=(from,to)=>{const arr=s.drafts[key];if(to<0||to>=arr.length)return;arr.splice(to,0,arr.splice(from,1)[0]);change();this.renderAnswer();};z.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [i,d]=b.dataset.move.split(',').map(Number);move(i,i+d);});let dragged;z.querySelectorAll('[data-order]').forEach(e=>{e.ondragstart=()=>dragged=Number(e.dataset.order);e.ondragover=ev=>ev.preventDefault();e.ondrop=ev=>{ev.preventDefault();move(dragged,Number(e.dataset.order));};});
const check=z.querySelector('.check');check.disabled=!this.ready(q,a)||s.rejected[key]===JSON.stringify(a)||s.status!=='playing';check.onclick=()=>{check.disabled=true;const result=s.check(key,q,s.drafts[key]);if(result==='correct'){this.active=null;if(s.status==='win')this.screen='win';this.render();this.message('Верно! '+(q.explanation||'Бочонок на месте.'));this.heroEffect(s.status==='win'?'win':'correct');}else if(result==='wrong'){if(s.status==='lose'){this.screen='lose';this.render();}else{z.querySelector('.answer-feedback').textContent='Пока неверно. Измените ответ и попробуйте ещё раз.';z.querySelector('.question-panel').classList.add('incorrect');this.root.querySelector('.game-lives').innerHTML=this.livesHTML();}this.heroEffect('wrong');}};
}
ready(q,a){return q.type==='text'?!!String(a).trim():Array.isArray(a)?a.length>0:!!a;}
}
