class LotoGame {
  constructor(root,project,{edit=false,onSelect=()=>{},onScratchChange=()=>{},onMoveCell=()=>{},onTicket=()=>{},onScreen=()=>{}}={}) {
    this.root=root;this.p=LotoUI.migrate(project);this.edit=edit;this.onSelect=onSelect;this.onScreen=onScreen;this.onScratchChange=onScratchChange;this.onMoveCell=onMoveCell;this.onTicket=onTicket;this.peek=new LotoTaskPeek(this);
    this.ticketPage=0;this.scratch=new LotoScratch(this);this.screen='start';this.session=null;this.active=null;this.heroEvent='hello';this.count=project.rules.min;this.render();
  }
  t(key){return LotoUI.t(this.p,key);}
  heroText(key){const value=this.p.hero.lines?.[key];return typeof value==='string'?value:this.t(key);}
  label(key){return LotoUI.screenText(this.p,key);}
  previewSession(){const s=new Loto.Session(this.p,Math.max(1,this.p.tickets.length));s.tickets=[...this.p.tickets];s.total=s.tickets.reduce((a,t)=>a+t.cells.filter(Boolean).length,0);return s;}
  setProject(p,structural=false){
    this.p=LotoUI.migrate(p);
    if(structural&&this.session){this.session=this.edit?this.previewSession():new Loto.Session(p,Math.min(this.session.tickets.length,p.tickets.length));}
    if(this.session){this.session.p=p;this.session.tickets=this.session.tickets.map(t=>p.tickets.find(x=>x.id===t.id)).filter(Boolean);}
    if(this.active&&!this.active.key.startsWith('bank:')){const [tid,ci]=this.active.key.split(':'),ticket=p.tickets.find(t=>t.id===tid);if(ticket){this.active.id=ticket.cells[Number(ci)];}else this.active=null;}
    if(this.active?.key.startsWith('bank:')&&!p.questions.some(q=>q.id===this.active.id))this.active=null;
    this.render();
  }
  style(){const d=this.p.design;this.root.classList.add('game');this.root.classList.toggle('editing',this.edit);this.root.lang=this.p.language;
    for(const k of ['table','accent','ticket','ink','cell','barrel','selected','correct','wrong','button','buttonText','modal','questionColor','answerColor'])this.root.style.setProperty('--'+k,d[k]);
    for(const [key,value] of Object.entries({'barrel-size':d.barrelSize+'px','hero-name-size':this.p.hero.nameSize+'px','hero-line-size':this.p.hero.lineSize+'px','radius':d.radius+'px','game-font':'"'+d.font+'"','game-size':d.fontSize+'px','title-size':d.titleSize+'px','instruction-size':d.instructionSize+'px','choose-size':d.chooseSize+'px','question-size':d.questionSize+'px','answer-size':d.answerSize+'px','table-opacity':d.tableOpacity/100}))this.root.style.setProperty('--'+key,value);
    this.root.style.setProperty('--barrel-blend',d.barrelImage?'normal':'multiply');this.root.style.setProperty('--barrel-image','url("'+(d.barrelImage||BarrelSkins[d.barrelSkin]||BarrelSkins.oak)+'")');const bg=this.root.querySelector('.game-background');bg.style.backgroundImage=d.background?`url("${d.background}")`:'';bg.style.backgroundSize='cover';bg.style.backgroundRepeat='no-repeat';bg.style.backgroundPosition=d.position;
    this.root.querySelector('.game-shade').style.opacity=d.dim/100;
    const box=this.root.parentElement;if(box?.classList.contains('game-viewport')){const rgb=[1,3,5].map(i=>parseInt(d.table.slice(i,i+2),16)).join(',');const felt=`rgba(${rgb},${d.tableOpacity/100})`,shade=`rgba(0,0,0,${d.dim/100})`;box.style.backgroundColor=d.table;box.style.backgroundImage=`linear-gradient(${shade},${shade}),linear-gradient(${felt},${felt})`+(d.background?`,url("${d.background}")`:'');box.style.backgroundSize='cover';box.style.backgroundPosition=d.position;box.style.backgroundRepeat='no-repeat';}

  }
  heroVisible(){const h=this.p.hero;return h.show&&h.image&&(h.placement==='both'||h.placement==='start'&&this.screen==='start'||h.placement==='game'&&this.screen!=='start');}
  heroMarkup(){const h=this.p.hero,{esc}=Loto;if(!this.heroVisible())return '';const event=['win','lose'].includes(this.screen)?(this.screen==='win'?'won':'lost'):this.active?'thinking':this.heroEvent;
    return `<aside class="hero-companion ${this.screen==='start'?'hero-intro':''}" data-key="hero"><div class="hero-portrait" style="--hero-size:${h.size}px"><img class="hero" src="${esc(h.image)}" alt="${esc(h.name||this.t('helper'))}" style="opacity:${h.opacity/100};transform:scaleX(${h.flip?-1:1})"></div><div class="hero-dialogue" ${['start','win','lose'].includes(this.screen)?'':'data-fit-box'}><div class="hero-dialogue-content"><strong>${esc(h.name||this.t('helper'))}</strong><p data-hero-message>${esc(this.heroText(event))}</p>${this.session&&this.screen!=='start'?`<span class="hero-shared">${esc(this.t('progress'))} · ${this.session.done.size} / ${this.session.total}</span>`:''}</div></div></aside>`;
  }
  bindHero(){const e=this.root.querySelector('.hero');if(!e)return;const h=this.p.hero;e.style.setProperty('--hero-color',h.color);e.style.setProperty('--hero-duration',h.duration+'s');e.style.setProperty('--hero-intensity',h.intensity+'px');e.onpointerenter=()=>this.heroEffect('hover');e.onclick=()=>{this.heroEffect('hover');if(this.edit)this.onSelect('Герой');};}
  heroEffect(event){const h=this.p.hero,e=this.root.querySelector('.hero');if(!e||!h[event])return;e.classList.remove('glow','blink','tint');void e.offsetWidth;e.classList.add(h.effect);clearTimeout(this.effectTimer);this.effectTimer=setTimeout(()=>e.classList.remove('glow','blink','tint'),h.duration*1000);}
  start(count){this.peek.close();const errors=Loto.validate(this.p);if(errors.length){this.message(errors[0]);return;}this.ticketPage=0;this.count=Math.max(this.p.rules.min,Math.min(this.p.rules.max,Number(count)));this.session=new Loto.Session(this.p,this.count);this.screen='game';this.active=null;this.heroEvent='hello';this.render();}
  show(screen){this.peek.close();this.screen=screen;this.active=null;if(screen!=='start'&&!this.session)this.session=this.edit?this.previewSession():new Loto.Session(this.p,this.p.rules.min);if(screen==='question'){const t=this.session.tickets.find(t=>t.cells.some(Boolean));if(t){const i=t.cells.findIndex(Boolean);this.active={key:t.id+':'+i,id:t.cells[i]};}}this.render();}
  focusCell(ticketId,index,reveal=false){if(!this.edit)return;this.session=this.previewSession();const t=this.p.tickets.find(t=>t.id===ticketId);if(!t)return;this.screen='game';this.ticketPage=this.session.tickets.findIndex(x=>x.id===ticketId);this.active={key:t.id+':'+index,id:t.cells[index]};this.peek.close();this.render();if(reveal)this.peek.open(this.active.key,true);}
  focusQuestion(id){if(!this.edit)return;if(this.active?.id===id){this.render();return;}const t=this.p.tickets.find(t=>t.cells.includes(id));if(t)return this.focusCell(t.id,t.cells.indexOf(id),true);this.session=this.previewSession();this.screen='game';this.active={key:'bank:'+id,id};this.render();}
  message(text){const e=this.root.querySelector('.game-message');if(e){e.textContent=text;this.root.fitToViewport?.();}}
  restart(home=false){if(!this.edit&&this.session?.status==='playing'&&(this.session.done.size||this.session.errors)&&!confirm(this.t('confirm')))return;this.peek.close();this.session=null;this.active=null;this.heroEvent='hello';this.screen=home?'start':'game';if(home)this.render();else this.start(this.p.rules.min);}
  livesHTML(){const r=this.p.rules,s=this.session;if(r.lifeFormat==='count')return Loto.esc(r.emoji)+' × '+s.lives;return Array.from({length:r.lives},(_,i)=>`<span style="opacity:${i<s.lives?1:r.faded?.2:0}">${Loto.esc(r.emoji)}</span>`).join('');}
  render(){const {esc}=Loto,math=LotoUI.math,p=this.p,s=this.session;this.onScreen(this.active?'question':this.screen);let content='';
    if(this.screen==='start'){
      this.count=Math.max(p.rules.min,Math.min(this.count,p.rules.max,p.tickets.length));
      content=`<div class="start-screen">${this.heroVisible()?this.heroMarkup():`<div class="barrel-illustration" aria-hidden="true"><i class="wood small">7</i><i class="wood large">42</i><i class="wood small">15</i></div>`}<h1 data-title>${esc(p.title)}</h1><p data-description>${esc(p.description)}</p><div class="start-divider"></div><p class="choose-label">${this.t('choose')}</p><div class="count-choices" role="group" aria-label="${this.t('choose')}">${Array.from({length:Math.max(0,Math.min(p.rules.max,p.tickets.length)-p.rules.min+1)},(_,i)=>i+p.rules.min).map(n=>`<button class="count-choice ${n===this.count?'chosen':''}" data-count="${n}" aria-pressed="${n===this.count}">${n}<small>${this.t(n===1?'ticket':n<5?'tickets':'manyTickets')}</small></button>`).join('')}</div><button class="gold-button start-play">${esc(this.label('startButton'))} <span>→</span></button><div class="game-instruction"><span>${esc(p.rules.emoji)} ${p.rules.lives} · ${this.t('lives')}</span><span>✦ ${this.t('pace')}</span></div><p class="game-message" role="status"></p></div>`;
    }else if(this.screen==='win'||this.screen==='lose'){
      const win=this.screen==='win';content=`<div class="end-screen">${this.heroVisible()?this.heroMarkup():`<span class="end-icon">${win?'🏆':'🌱'}</span>`}<div class="game-kicker">${this.t(win?'complete':'retry')}</div><h1>${esc(this.label(win?'winTitle':'loseTitle'))}</h1><p>${esc(this.label(win?'winText':'loseText'))}</p><div class="end-stats"><div><strong>${s?.done.size||0} / ${s?.total||0}</strong><span>${this.t('collected')}</span></div><div><strong>${s?.errors||0}</strong><span>${this.t('errors')}</span></div></div><button class="gold-button again">${esc(this.label('again'))}</button><button class="text-button home">${this.t('home')}</button></div>`;
    }else if(s){
      this.ticketPage=Math.max(0,Math.min(this.ticketPage,s.tickets.length-1));
      content=`<header class="game-header"><div><span class="game-kicker">${this.t('kicker')}</span><h2 data-title>${esc(p.title)}</h2></div><div class="game-lives" aria-label="${this.t('lives')}">${this.livesHTML()}</div></header><div class="game-progress"><span>${this.t('collected')} <b>${s.done.size} / ${s.total}</b></span><button class="text-button restart">↶ ${this.t('restart')}</button></div><div class="progress-track"><i style="width:${s.total?s.done.size/s.total*100:0}%"></i></div>${this.heroMarkup()}<div class="answer-zone"></div><nav class="ticket-pages" aria-label="${this.t('ticketNav')}">${s.tickets.map((t,i)=>`<button class="${i===this.ticketPage?'active':''}" data-ticket-page="${i}">${esc(t.name)} <small>${t.cells.filter((id,j)=>id&&s.done.has(t.id+':'+j)).length}/${t.cells.filter(Boolean).length}</small></button>`).join('')}<button class="scratch-open">✎ ${this.t('scratch')}</button></nav><div class="ticket-workspace"><div class="tickets">${s.tickets.slice(this.ticketPage,this.ticketPage+1).map(t=>`<section class="loto-ticket" data-key="${esc(t.id)}"><div class="ticket-heading"><span>✦ ${esc(t.name)}</span><span>${t.cells.filter((q,i)=>q&&s.done.has(t.id+':'+i)).length} / ${t.cells.filter(Boolean).length}</span></div><div class="ticket-grid" style="--cols:${t.cols};--rows:${t.rows}">${t.cells.map((id,i)=>{const q=p.questions.find(q=>q.id===id),key=t.id+':'+i,done=s.done.has(key),selected=this.active?.key===key;return q||this.edit?`<button class="ticket-cell ${q?'':'empty'} ${done?'closed':''} ${selected?'active':''}" data-cell="${esc(key)}" data-q="${esc(id||'')}" ${done&&!this.edit?'disabled':''} >${this.edit?`<small class="cell-number">${i+1}</small>`:''}${done?`<span class="mini-barrel">${LotoUI.plainAnswer(q?.stamp)}</span>`:`<span data-q-label="${esc(id||'')}" class="${q?.labelMedia?.image?'has-cell-image':''}">${q?.labelMedia?.image?`<img class="cell-label-image" src="${esc(q.labelMedia.image)}" alt="${esc(q.label||q.text)}">`: ''}<span class="cell-label-text">${q?math(q.label):'+'}</span></span>`}</button>`:'<div class="ticket-cell empty" aria-hidden="true"><i>✦</i></div>';}).join('')}</div></section>`).join('')}</div></div><p class="game-message" role="status" aria-live="polite">${this.t('chooseCell')}</p>`;
    }
    const zone=this.root.querySelector('.answer-zone'),answerHTML=zone?.innerHTML||'';content=content.replace('<div class="answer-zone"></div>','<div class="answer-zone">'+answerHTML+'</div>');
    LotoUI.patch(this.root,`<div class="game-background" data-key="background"></div><div class="game-felt" data-key="felt"></div><div class="game-shade" data-key="shade"></div><div class="table-stitch" data-key="stitch"></div><div class="game-content ${this.screen==='start'||this.screen==='win'||this.screen==='lose'?'screen-layout':this.heroVisible()?'board-layout with-hero':'board-layout'}" data-key="content" ${this.screen==='start'||this.screen==='win'||this.screen==='lose'?'data-fit-box':''}>${content}</div>${this.scratch.markup()}${this.peek.markup()}${p.notoAttribution?'<div class="noto-credit"><a data-noto-source target="_blank" rel="noopener">Noto Emoji · Google</a> · <a data-noto-license target="_blank" rel="noopener">CC BY 4.0</a> · размер изменён</div>':''}`);
    const credit=this.root.querySelector('.noto-credit');if(credit){credit.querySelector('[data-noto-source]').href='https://googlefonts.github.io/noto-emoji-animation/';credit.querySelector('[data-noto-license]').href='https://creativecommons.org/licenses/by/4.0/';}this.style();this.bindHero();this.scratch.bind();this.peek.bind();const c=this.root.querySelector('.game-content');
    c.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{this.count=Number(b.dataset.count);this.render();});
    c.querySelectorAll('[data-ticket-page]').forEach(b=>b.onclick=()=>{this.peek.close();this.ticketPage=Number(b.dataset.ticketPage);this.active=null;this.render();if(this.edit)this.onTicket(this.session.tickets[this.ticketPage].id);});const scratch=c.querySelector('.scratch-open');if(scratch)scratch.onclick=()=>{this.scratch.open=true;this.render();};const start=c.querySelector('.start-play');if(start)start.onclick=()=>this.start(this.count);
    const again=c.querySelector('.again');if(again)again.onclick=()=>this.restart();
    const home=c.querySelector('.home');if(home)home.onclick=()=>this.restart(true);
    const restart=c.querySelector('.restart');if(restart)restart.onclick=()=>this.restart();
    c.querySelectorAll('[data-cell]').forEach(b=>b.onclick=event=>{if(!this.edit&&s.status!=='playing')return;this.active={key:b.dataset.cell,id:b.dataset.q||null};this.heroEvent='thinking';this.render();if(this.edit)this.onSelect('Задания',this.active.id,this.active.key);if(this.p.questions.find(q=>q.id===this.active.id)?.showDetails!==false)this.peek.open(this.active.key,true);else this.peek.close();});
    if(this.edit)LotoCellDrag.bind(c,'[data-cell]',el=>{const [ticketId,index]=el.dataset.cell.split(':');return {ticketId,index:Number(index),cols:this.p.tickets.find(t=>t.id===ticketId).cols};},this.onMoveCell,()=>this.peek.close());else LotoCellDrag.unbind(c,'[data-cell]');const current=c.querySelector('.answer-zone');if(current)this.renderAnswer();this.root.fitToViewport?.();
  }
  renderAnswer(){const z=this.root.querySelector('.answer-zone');if(!z)return;const {esc}=Loto,math=LotoUI.math;
    if(!this.active){this.answerRevealKey=null;LotoUI.patch(z,`<div class="barrel-rest"><i class="wood">?</i><div><strong>${this.t('discovery')}</strong><p>${this.t('hint')}</p></div></div>`);return;}
    const s=this.session,{key,id}=this.active,q=this.p.questions.find(q=>q.id===id);
    if(!q){LotoUI.patch(z,`<div class="question-panel"><h3>${this.t('empty')}</h3><p>${this.t('editHint')}</p><div class="inline-type-picker">${Object.keys(Loto.types).map(type=>`<button data-create-type="${type}">${esc(this.t(type==='multiple'?'multipleType':type==='order'?'orderType':type))}</button>`).join('')}</div></div>`);z.querySelectorAll('[data-create-type]').forEach(b=>b.onclick=()=>this.onSelect('Задания',null,key,b.dataset.createType));return;}

    if(q.type==='audio'&&q.answerRequired===false){LotoUI.patch(z,`<div class="question-panel audio-only-panel"><div class="question-top"><span>${esc(this.t('audio'))}</span>${q.showDetails!==false&&!s.done.has(key)?`<button class="open-task-details text-button">ⓘ ${esc(this.t('taskDetails'))}</button>`:''}<button class="close-question" aria-label="${this.t('close')}">×</button></div>${q.showDetails===false?LotoMedia.html(q.media):''}<div class="audio-only-message"><span aria-hidden="true">♫</span><p>${esc(this.t('noAnswers'))}</p></div><button class="gold-button complete-audio" ${s.status!=='playing'||s.done.has(key)?'disabled':''}>${esc(this.t('listened'))}</button></div>`);if(z.querySelector('.open-task-details'))z.querySelector('.open-task-details').onclick=()=>this.peek.open(key,true);z.querySelector('.close-question').onclick=()=>{this.active=null;this.peek.close();this.render();};z.querySelector('.complete-audio').onclick=()=>{if(s.complete(key,q)!=='complete')return;this.peek.close();this.active=null;this.heroEvent='cheer';if(s.status==='win')this.screen='win';this.render();this.message(this.t('taskComplete')+' '+(q.explanation||''));this.heroEffect(s.status==='win'?'win':'correct');};this.root.fitToViewport?.();return;}
    const opts=q.options||[],ids=opts.map(o=>o.id);
    if(!s.orders[key]||s.orders[key].length!==ids.length||s.orders[key].some(id=>!ids.includes(id))){s.orders[key]=this.edit?ids:Loto.shuffle(ids);if(!this.edit&&q.type==='order'&&JSON.stringify(s.orders[key])===JSON.stringify(ids))s.orders[key].reverse();}
    if(!(key in s.drafts))s.drafts[key]=q.type==='order'?[...s.orders[key]]:q.type==='multiple'?[]:'';
    const a=s.drafts[key];
    LotoUI.patch(z,`<div class="question-panel"><div class="question-top"><span>${esc(this.t(q.type==='multiple'?'multipleType':q.type==='order'?'orderType':q.type))}</span>${q.showDetails!==false&&!s.done.has(key)?`<button class="open-task-details text-button">ⓘ ${esc(this.t('taskDetails'))}</button>`:''}<button class="close-question" aria-label="${this.t('close')}">×</button></div><div class="answer-fit" data-fit-box><div class="answer-inputs">${q.showDetails===false?LotoMedia.html(q.media,{compact:true}):''}${['text','passage'].includes(q.type)?`<i class="wood neutral">?</i><input class="written-answer" aria-label="${this.t('answer')}" placeholder="${this.t('enter')}" value="${esc(a)}" autocomplete="off">`:(q.type==='order'?a:s.orders[key]).map((id,i)=>{const o=opts.find(o=>o.id===id);if(!o)return '';return q.type==='order'?`<div class="order-item" draggable="true" data-order="${i}">${LotoMedia.html(o.media,{compact:true})}<i class="wood">${LotoUI.plainAnswer(o.text)}</i><span><button data-move="${i},-1" aria-label="${this.t('left')}" ${i===0?'disabled':''}>←</button><button data-move="${i},1" aria-label="${this.t('right')}" ${i===a.length-1?'disabled':''}>→</button></span></div>`:`<div class="answer-choice">${LotoMedia.html(o.media,{compact:true})}<button class="wood answer-barrel ${(q.type==='multiple'?a.includes(id):a===id)?'chosen':''}" data-answer="${esc(id)}" aria-pressed="${q.type==='multiple'?a.includes(id):a===id}">${LotoUI.plainAnswer(o.text)||String(i+1)}</button></div>`;}).join('')}</div></div><div class="check-row"><span class="answer-feedback" role="status">${this.t(q.type==='multiple'?'multiple':q.type==='order'?'order':'chooseAnswer')}</span><button class="gold-button check">${esc(this.label('checkLabel'))}</button></div></div>`);
    z.querySelectorAll('[data-create-type]').forEach(b=>b.onclick=()=>this.onSelect('Задания',id,key,b.dataset.createType));
    if(z.querySelector('.open-task-details'))z.querySelector('.open-task-details').onclick=()=>this.peek.open(key,true);z.querySelector('.close-question').onclick=()=>{this.active=null;this.peek.close();this.render();};
    const change=()=>{delete s.rejected[key];z.querySelector('.check').disabled=!this.ready(q,s.drafts[key]);};
    z.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const v=b.dataset.answer;s.drafts[key]=q.type==='multiple'?(s.drafts[key].includes(v)?s.drafts[key].filter(x=>x!==v):[...s.drafts[key],v]):v;change();this.renderAnswer();});
    const input=z.querySelector('.written-answer');if(input)input.oninput=()=>{s.drafts[key]=input.value;change();};
    const move=(from,to)=>{const arr=s.drafts[key];if(!Number.isInteger(from)||to<0||to>=arr.length)return;arr.splice(to,0,arr.splice(from,1)[0]);change();this.renderAnswer();};z.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [i,d]=b.dataset.move.split(',').map(Number);move(i,i+d);});let dragged;z.querySelectorAll('[data-order]').forEach(e=>{e.ondragstart=()=>dragged=Number(e.dataset.order);e.ondragover=ev=>ev.preventDefault();e.ondrop=ev=>{ev.preventDefault();move(dragged,Number(e.dataset.order));};});
    const button=z.querySelector('.check');button.disabled=!this.ready(q,a)||s.rejected[key]===JSON.stringify(a)||s.status!=='playing';button.onclick=()=>{button.disabled=true;const result=s.check(key,q,s.drafts[key]);if(result==='correct'){this.peek.close();this.active=null;this.heroEvent='cheer';if(s.status==='win')this.screen='win';this.render();this.message(this.t('correct')+' '+(q.explanation||''));this.heroEffect(s.status==='win'?'win':'correct');}else if(result==='wrong'){this.heroEvent='encourage';if(s.status==='lose'){this.screen='lose';this.render();}else{z.querySelector('.answer-feedback').textContent=this.t('wrong');z.querySelector('.question-panel').classList.add('incorrect');this.root.querySelector('.game-lives').innerHTML=this.livesHTML();const msg=this.root.querySelector('[data-hero-message]');if(msg)msg.textContent=this.heroText('encourage');}this.heroEffect('wrong');}};this.animateAnswers(key);this.root.fitToViewport?.();
  }
  animateAnswers(key){const d=this.p.design,token=key+':'+d.answerAnimation+':'+d.animationDuration;if(this.answerRevealKey===token)return;this.answerRevealKey=token;const reduced=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced||d.answerAnimation==='none')return;const frames={fade:[{opacity:0},{opacity:1}],rise:[{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'translateY(0)'}],zoom:[{opacity:0,transform:'scale(.88)'},{opacity:1,transform:'scale(1)'}]};this.root.querySelectorAll('.answer-choice,.order-item,.written-answer').forEach((el,i)=>el.animate?.(frames[d.answerAnimation]||frames.fade,{duration:d.animationDuration,delay:i*45,easing:'ease-out',fill:'backwards'}));}
  ready(q,a){return ['text','passage'].includes(q.type)?!!String(a).trim():Array.isArray(a)?a.length>0:!!a;}
}
