class LotoReader {
  constructor(game){this.game=game;this.key=null;this.q=null;this.page=0;this.tool='pen';this.color='#255cce';this.notes={};this.pages=[];}
  snapshot(){return this.notes;}
  restore(notes){this.notes=notes&&typeof notes==='object'&&!Array.isArray(notes)?notes:{};}
  textPages(text){const canvas=document.createElement('canvas'),ctx=canvas.getContext?.('2d');if(ctx)ctx.font='24px Arial';const lines=[];for(const paragraph of String(text).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){for(const part of word.match(/.{1,50}/gu)||['']){const next=line?line+' '+part:part;if(line&&(ctx?.measureText?ctx.measureText(next).width>940:next.length>65)){lines.push(line);line=part;}else line=next;}}lines.push(line);}const pages=[];for(let i=0;i<lines.length;i+=13)pages.push({text:lines.slice(i,i+13).join('\n')});return pages.length?pages:[{text:''}];}
  open(key,q){if(this.game.session?.done.has(key))return;const source=q.pdf?.id||q.passage||q.text;this.key=key;this.q=q;this.page=0;this.pages=q.pdf?.pages?.length?q.pdf.pages.map(image=>({image})):this.textPages(q.passage||q.text);if(!this.notes[key]||this.notes[key].source!==source)this.notes[key]={source,pages:{}};this.game.render();}
  close(){this.key=null;this.q=null;const layer=this.game.root.querySelector('.reading-layer');if(layer)layer.hidden=true;}
  sync(){if(!this.key)return;const [tid,index]=this.key.split(':'),id=this.key.startsWith('bank:')?this.key.slice(5):this.game.p.tickets.find(t=>t.id===tid)?.cells[Number(index)],q=this.game.p.questions.find(q=>q.id===id);if(!q||q.type!=='passage'){this.close();return;}this.q=q;const source=q.pdf?.id||q.passage||q.text;if(this.notes[this.key]?.source!==source){this.notes[this.key]={source,pages:{}};this.page=0;this.pages=q.pdf?.pages?.length?q.pdf.pages.map(image=>({image})):this.textPages(q.passage||q.text);}}
  markup(){this.sync();const t=k=>Loto.esc(this.game.t(k));if(!this.key)return '<section class="reading-layer" hidden></section>';const page=this.pages[this.page]||{},q=this.q;return `<section class="reading-layer" role="dialog" aria-label="${t('oral')}"><header><strong>${Loto.esc(q?.label||this.game.t('oral'))}</strong><button data-reading="close" aria-label="${t('close')}">×</button></header><div class="reading-toolbar"><button data-reading="pen" class="${this.tool==='pen'?'active':''}">✎ ${t('pencil')}</button><button data-reading="highlight" class="${this.tool==='highlight'?'active':''}">▰ ${t('highlight')}</button><input type="color" aria-label="Цвет отметки" value="${this.color}"><button data-reading="undo">↶</button><button data-reading="clear">${t('clear')}</button><span>${t('oralHint')}</span></div><div class="reading-body"><div class="reading-sheet">${page.image?`<img src="${Loto.esc(page.image)}" alt="${Loto.esc(q.pdf.name)} · ${this.page+1}">`:`<div class="reading-text">${Loto.esc(page.text)}</div>`}<canvas width="1000" height="480" aria-label="Подчёркивание и выделение материала"></canvas></div></div><footer><button data-reading="previous" ${this.page===0?'disabled':''}>← ${t('previous')}</button><span>${this.page+1} / ${this.pages.length}</span><button data-reading="next" ${this.page>=this.pages.length-1?'disabled':''}>${t('next')} →</button><button class="gold-button" data-reading="done">${t('completed')}</button></footer></section>`;}
  strokes(){if(!this.key||!this.notes[this.key])return [];return this.notes[this.key].pages[this.page]??=[];}
  changed(){this.game.scratch.changed();}
  bind(){const area=this.game.root.querySelector('.reading-layer');if(!area||!this.key)return;if(!['game','question'].includes(this.game.screen)||this.game.session?.done.has(this.key)){this.close();return;}this.canvas=area.querySelector('canvas');this.ctx=this.canvas?.getContext?.('2d');area.querySelectorAll('[data-reading]').forEach(b=>b.onclick=()=>{const a=b.dataset.reading;if(a==='close'){this.close();return;}if(a==='done'){this.game.completeTask(this.key,this.q);return;}if(a==='previous')this.page=Math.max(0,this.page-1);if(a==='next')this.page=Math.min(this.pages.length-1,this.page+1);if(a==='pen'||a==='highlight')this.tool=a;if(a==='undo'){this.strokes().pop();this.changed();}if(a==='clear'){this.notes[this.key].pages[this.page]=[];this.changed();}this.game.render();});area.querySelector('input').oninput=e=>this.color=e.target.value;area.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();this.close();}};const point=e=>{const r=this.canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};let stroke=null;this.canvas.onpointerdown=e=>{e.preventDefault();this.canvas.setPointerCapture?.(e.pointerId);stroke={tool:this.tool,color:this.tool==='highlight'?'#ffdb38':this.color,points:[point(e)]};this.strokes().push(stroke);this.draw();};this.canvas.onpointermove=e=>{if(!stroke)return;stroke.points.push(point(e));this.draw();};this.canvas.onpointerup=this.canvas.onpointercancel=()=>{if(stroke){stroke=null;this.changed();}};this.draw();}
  draw(){const c=this.ctx;if(!c)return;c.clearRect(0,0,1000,480);for(const s of this.strokes()){if(!Array.isArray(s.points))continue;c.globalAlpha=s.tool==='highlight'?.3:1;c.strokeStyle=s.color;c.lineWidth=s.tool==='highlight'?18:3;c.lineCap='round';c.lineJoin='round';c.beginPath();s.points.forEach(([x,y],i)=>i?c.lineTo(x*1000,y*480):c.moveTo(x*1000,y*480));if(s.points.length===1)c.lineTo(s.points[0][0]*1000+.1,s.points[0][1]*480+.1);c.stroke();}c.globalAlpha=1;}
}
