class LotoScratch {
  constructor(game){this.game=game;this.strokes=[];this.open=false;this.color='#243858';this.width=3;this.eraser=false;this.revision=0;}
  snapshot(){return {reading:this.game.reader.snapshot(),strokes:this.strokes,color:this.color,width:this.width,eraser:this.eraser};}
  restore(data){this.game.reader.restore(data?.reading);this.strokes=Array.isArray(data?.strokes)?data.strokes:[];this.color=/^#[0-9a-f]{6}$/i.test(data?.color)?data.color:'#243858';this.width=Math.max(1,Math.min(12,Number(data?.width)||3));this.eraser=!!data?.eraser;this.revision++;this.draw();}
  changed(){this.revision++;this.game.onScratchChange(this.snapshot());}

  markup(){return `<section class="scratch-layer" ${this.open?'':'hidden'} aria-label="Черновик"><header><strong>${this.game.t('scratch')}</strong><button data-scratch="close" aria-label="${this.game.t('close')}">×</button></header><div class="scratch-tools"><button data-scratch="pen" class="${this.eraser?'':'active'}">✎ ${this.game.t('pencil')}</button><button data-scratch="eraser" class="${this.eraser?'active':''}">${this.game.t('eraser')}</button><input type="color" value="${this.color}" aria-label="Цвет карандаша"><input type="range" min="1" max="12" value="${this.width}" aria-label="Толщина карандаша"><button data-scratch="undo">↶</button><button data-scratch="clear">${this.game.t('clear')}</button></div><canvas width="1000" height="600" aria-label="Поле для решения заданий"></canvas></section>`;}
  bind(){const area=this.game.root.querySelector('.scratch-layer');if(!area)return;const canvas=area.querySelector('canvas'),ctx=canvas.getContext?.('2d');this.canvas=canvas;this.ctx=ctx;
    area.querySelectorAll('[data-scratch]').forEach(b=>b.onclick=()=>{const action=b.dataset.scratch;if(action==='close')this.open=false;else if(action==='pen')this.eraser=false;else if(action==='eraser')this.eraser=true;else if(action==='undo')this.strokes.pop();else if(action==='clear')this.strokes=[];this.changed();this.game.render();});
    area.querySelector('input[type=color]').oninput=e=>{this.color=e.target.value;this.changed();};area.querySelector('input[type=range]').oninput=e=>{this.width=Number(e.target.value);this.changed();};
    const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height];};let stroke=null;
    canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture?.(e.pointerId);stroke={color:this.color,width:this.width,erase:this.eraser,points:[point(e)]};this.strokes.push(stroke);this.draw();};canvas.onpointermove=e=>{if(!stroke)return;stroke.points.push(point(e));this.draw();};canvas.onpointerup=canvas.onpointercancel=()=>{if(stroke){stroke=null;this.changed();}};this.draw();
  }
  draw(){if(!this.ctx)return;const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);for(const s of this.strokes){c.globalCompositeOperation=s.erase?'destination-out':'source-over';c.strokeStyle=s.color;c.fillStyle=s.color;c.lineWidth=s.erase?s.width*5:s.width;c.lineCap='round';c.lineJoin='round';c.beginPath();s.points.forEach(([x,y],i)=>i?c.lineTo(x*w,y*h):c.moveTo(x*w,y*h));if(s.points.length===1){const [x,y]=s.points[0];c.lineTo(x*w+.1,y*h+.1);}c.stroke();}c.globalCompositeOperation='source-over';}
}
