'use strict';
const LotoUI = (() => {
  const languages={ru:'Русский',en:'English',uk:'Українська',kk:'Қазақша'};
  const fonts=['Nunito','Roboto','Open Sans','Arial','Verdana','Georgia','Trebuchet MS','Tahoma','Times New Roman','Courier New','Palatino','Garamond','Helvetica','Impact','Comic Sans MS'];
  const gameWords={
    ru:{eyebrow:'УЧИСЬ · ИГРАЙ · ПОБЕЖДАЙ',kicker:'УЧЕБНОЕ ЛОТО',choose:'Сколько билетов возьмём?',ticket:'билет',tickets:'билета',manyTickets:'билетов',pace:'В своём темпе',lives:'Жизни',collected:'Собрано бочонков',errors:'Ошибок',home:'На главный экран',restart:'Начать заново',chooseCell:'Выберите задание на любом билете',discovery:'Каждый бочонок — новое открытие',hint:'Нажмите на клетку и найдите правильный ответ',answer:'Ваш ответ',enter:'Введите ответ…',multiple:'Отметьте все подходящие варианты',order:'Перетащите бочонки или используйте стрелки',chooseAnswer:'Выберите или введите ответ',correct:'Верно!',wrong:'Пока неверно. Измените ответ и попробуйте ещё раз.',confirm:'Завершить текущую игру? Прогресс будет сброшен.',complete:'ЛОТО СОБРАНО',retry:'НОВАЯ ПОПЫТКА — НОВЫЙ ШАНС',helper:'Твой напарник',hello:'Давай соберём лото вместе!',thinking:'Думаем вместе. Выбери ответ!',cheer:'Отличный ход! Продолжаем!',encourage:'Не сдавайся, у тебя получится!',won:'Мы справились! Все бочонки собраны.',lost:'Отдохнём и попробуем ещё раз.',progress:'Наш общий прогресс',single:'Один ответ',multipleType:'Несколько ответов',text:'Ввод ответа',orderType:'По порядку',close:'Закрыть задание',left:'Переместить влево',right:'Переместить вправо',editHint:'Выберите тип задания и заполните поля слева',empty:'Пустая клетка',select:'Выбрать задание'},
    en:{eyebrow:'LEARN · PLAY · SUCCEED',kicker:'LEARNING LOTTO',choose:'How many tickets?',ticket:'ticket',tickets:'tickets',manyTickets:'tickets',pace:'At your own pace',lives:'Lives',collected:'Barrels collected',errors:'Mistakes',home:'Home',restart:'Restart',chooseCell:'Choose a task on any ticket',discovery:'Every barrel is a new discovery',hint:'Select a cell and find the correct answer',answer:'Your answer',enter:'Enter an answer…',multiple:'Select all correct options',order:'Drag the barrels or use the arrows',chooseAnswer:'Choose or enter an answer',correct:'Correct!',wrong:'Not yet. Change your answer and try again.',confirm:'End this game? Your progress will be reset.',complete:'LOTTO COMPLETE',retry:'A NEW TRY, A NEW CHANCE',helper:'Your teammate',hello:'Let’s complete the lotto together!',thinking:'Let’s think together. Choose an answer!',cheer:'Great move! Keep going!',encourage:'Keep trying, you can do it!',won:'We did it! Every barrel is collected.',lost:'Let’s take a break and try again.',progress:'Our shared progress',single:'Single answer',multipleType:'Multiple answers',text:'Text answer',orderType:'Put in order',close:'Close task',left:'Move left',right:'Move right',editHint:'Choose a task type and edit the fields on the left',empty:'Empty cell',select:'Choose a task'},
    uk:{eyebrow:'НАВЧАЙСЯ · ГРАЙ · ПЕРЕМАГАЙ',kicker:'НАВЧАЛЬНЕ ЛОТО',choose:'Скільки квитків візьмемо?',ticket:'квиток',tickets:'квитки',manyTickets:'квитків',pace:'У власному темпі',lives:'Життя',collected:'Зібрано бочонків',errors:'Помилок',home:'На головний екран',restart:'Почати знову',chooseCell:'Виберіть завдання на будь-якому квитку',discovery:'Кожен бочонок — нове відкриття',hint:'Натисніть на клітинку та знайдіть правильну відповідь',answer:'Ваша відповідь',enter:'Введіть відповідь…',multiple:'Позначте всі правильні варіанти',order:'Перетягніть бочонки або скористайтеся стрілками',chooseAnswer:'Виберіть або введіть відповідь',correct:'Правильно!',wrong:'Поки неправильно. Змініть відповідь і спробуйте ще раз.',confirm:'Завершити гру? Прогрес буде скинуто.',complete:'ЛОТО ЗІБРАНО',retry:'НОВА СПРОБА — НОВИЙ ШАНС',helper:'Твій напарник',hello:'Зберімо лото разом!',thinking:'Думаємо разом. Вибери відповідь!',cheer:'Чудовий хід! Продовжуємо!',encourage:'Не здавайся, у тебе вийде!',won:'Ми впоралися! Усі бочонки зібрані.',lost:'Відпочинемо та спробуємо ще раз.',progress:'Наш спільний прогрес',single:'Одна відповідь',multipleType:'Кілька відповідей',text:'Введення відповіді',orderType:'За порядком',close:'Закрити завдання',left:'Перемістити ліворуч',right:'Перемістити праворуч',editHint:'Виберіть тип завдання та заповніть поля ліворуч',empty:'Порожня клітинка',select:'Вибрати завдання'},
    kk:{eyebrow:'ҮЙРЕН · ОЙНА · ЖЕҢ',kicker:'ОҚУ ЛОТОСЫ',choose:'Неше билет аламыз?',ticket:'билет',tickets:'билет',manyTickets:'билет',pace:'Өз қарқыныңмен',lives:'Мүмкіндіктер',collected:'Жиналған бөшкелер',errors:'Қателер',home:'Басты экранға',restart:'Қайта бастау',chooseCell:'Кез келген билеттен тапсырма таңдаңыз',discovery:'Әр бөшке — жаңа жаңалық',hint:'Ұяшықты басып, дұрыс жауапты табыңыз',answer:'Сіздің жауабыңыз',enter:'Жауапты енгізіңіз…',multiple:'Барлық дұрыс жауаптарды таңдаңыз',order:'Бөшкелерді жылжытыңыз немесе көрсеткілерді қолданыңыз',chooseAnswer:'Жауапты таңдаңыз немесе енгізіңіз',correct:'Дұрыс!',wrong:'Әзірге қате. Жауапты өзгертіп, қайталап көріңіз.',confirm:'Ойынды аяқтау керек пе? Нәтиже жойылады.',complete:'ЛОТО ЖИНАЛДЫ',retry:'ЖАҢА ӘРЕКЕТ — ЖАҢА МҮМКІНДІК',helper:'Сенің серігің',hello:'Лотоны бірге жинайық!',thinking:'Бірге ойланайық. Жауапты таңда!',cheer:'Керемет! Жалғастырайық!',encourage:'Берілме, сенің қолыңнан келеді!',won:'Біз орындадық! Барлық бөшке жиналды.',lost:'Демалып, қайта байқап көрейік.',progress:'Біздің ортақ нәтижеміз',single:'Бір жауап',multipleType:'Бірнеше жауап',text:'Жауапты енгізу',orderType:'Ретімен қою',close:'Тапсырманы жабу',left:'Солға жылжыту',right:'Оңға жылжыту',editHint:'Тапсырма түрін таңдап, сол жақтағы өрістерді толтырыңыз',empty:'Бос ұяшық',select:'Тапсырма таңдау'}
  };
  const screenDefaults={
    ru:{startButton:'Начать игру',again:'Играть снова',winTitle:'Блестящая победа!',winText:'Все бочонки на своих местах. Отличная работа!',loseTitle:'Попробуем ещё раз?',loseText:'Каждая попытка делает тебя сильнее.',checkLabel:'Проверить'},
    en:{startButton:'Start playing',again:'Play again',winTitle:'A brilliant victory!',winText:'Every barrel is in place. Well done!',loseTitle:'Shall we try again?',loseText:'Every attempt helps you grow.',checkLabel:'Check answer'},
    uk:{startButton:'Почати гру',again:'Грати знову',winTitle:'Блискуча перемога!',winText:'Усі бочонки на своїх місцях. Чудова робота!',loseTitle:'Спробуємо ще раз?',loseText:'Кожна спроба робить тебе сильнішим.',checkLabel:'Перевірити'},
    kk:{startButton:'Ойынды бастау',again:'Қайта ойнау',winTitle:'Керемет жеңіс!',winText:'Барлық бөшке өз орнында. Жарайсың!',loseTitle:'Қайта байқап көрейік пе?',loseText:'Әр әрекет сені шыңдайды.',checkLabel:'Тексеру'}
  };
  function t(p,key){return (gameWords[p.language||'ru']||gameWords.ru)[key]||gameWords.ru[key]||key;}
  function screenText(p,key){const value=key==='checkLabel'?p.design.checkLabel:p.screens[key];return Object.values(screenDefaults).some(d=>d[key]===value)?screenDefaults[p.language||'ru'][key]:value;}
  function migrate(p){if(!p||p.version!==1)return p;const d=p.design,h=p.hero;if(d){d.fontSize??=18;d.questionSize??=22;d.answerSize??=22;d.tableOpacity??=0;d.questionColor??=d.ink;d.answerColor??=d.ink;d.barrelSkin??='oak';d.barrelImage??='';}p.language??='ru';p.editorLanguage='ru';for(const q of p.questions||[]){q.media??={image:'',audio:''};q.passage??='';for(const o of q.options||[])o.media??={image:'',audio:''};}if(h){h.placement??='both';h.name??='';}return p;}
  function math(text){const input=String(text??''),re=/\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;let html='',last=0,m;while((m=re.exec(input))){html+=Loto.esc(input.slice(last,m.index)).replace(/\n/g,'<br>');try{if(typeof katex==='undefined')throw Error('KaTeX unavailable');html+=katex.renderToString(m[1]??m[2],{displayMode:!!m[1],throwOnError:true,trust:false,strict:'ignore',maxExpand:1000,maxSize:20,output:'htmlAndMathml'});}catch{html+='<span class="math-error" title="Проверьте LaTeX и скобки">'+Loto.esc(m[0])+'</span>';}last=re.lastIndex;}return html+Loto.esc(input.slice(last)).replace(/\n/g,'<br>');}
  // Reconcile existing nodes: preserve the scene, focused controls and scroll positions.
  function patch(target,html){const template=document.createElement('template');template.innerHTML=html;
    const sync=(parent,next)=>{let i=0;while(i<next.childNodes.length){const n=next.childNodes[i],old=parent.childNodes[i];if(!old){parent.append(n.cloneNode(true));i++;continue;}if(old.nodeType!==n.nodeType||old.nodeName!==n.nodeName){old.replaceWith(n.cloneNode(true));i++;continue;}if(n.nodeType===3){if(old.nodeValue!==n.nodeValue)old.nodeValue=n.nodeValue;}else if(n.nodeType===1){for(const a of [...old.attributes])if(!n.hasAttribute(a.name))old.removeAttribute(a.name);for(const a of [...n.attributes])if(old.getAttribute(a.name)!==a.value)old.setAttribute(a.name,a.value);if(old.tagName==='INPUT'&&document.activeElement!==old&&old.value!==n.value)old.value=n.value;sync(old,n);}i++;}while(parent.childNodes.length>next.childNodes.length)parent.lastChild.remove();};sync(target,template.content);}
  function httpsURL(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||['localhost','127.0.0.1','[::1]'].includes(u.hostname))throw Error('Нужен HTTPS-адрес опубликованной игры.');return u.href;}
  function embedCode({html='',url='',mode='inline',width=960,height=720,responsive=true}){const w=responsive?'100%':Math.max(360,Math.min(2400,Number(width)||960)),h=Math.max(360,Math.min(2400,Number(height)||720));const source=mode==='url'?'src="'+Loto.esc(httpsURL(url))+'"':'srcdoc="'+Loto.esc(html)+'"';return `<iframe ${source} title="Learning Lotto" width="${w}" height="100%" scrolling="no" style="display:block;border:0;width:${responsive?'100%':w+'px'};height:100%;aspect-ratio:${Number(width)||960}/${h};max-width:100%;border-radius:16px;overflow:hidden" allowfullscreen></iframe>`;}
  function plainAnswer(text){return Loto.esc(String(text??'').replace(/\$+/g,''));}
Object.assign(gameWords.ru,{audio:'Аудиозадание',passage:'Готовый текст',scratch:'Черновик',pencil:'Карандаш',eraser:'Ластик',clear:'Очистить',listen:'Прослушайте запись и выберите ответ',ticketNav:'Билеты'});
Object.assign(gameWords.en,{audio:'Audio task',passage:'Reading task',scratch:'Scratchpad',pencil:'Pencil',eraser:'Eraser',clear:'Clear',listen:'Listen and choose an answer',ticketNav:'Tickets'});
Object.assign(gameWords.uk,{audio:'Аудіозавдання',passage:'Готовий текст',scratch:'Чернетка',pencil:'Олівець',eraser:'Гумка',clear:'Очистити',listen:'Прослухайте запис і виберіть відповідь',ticketNav:'Квитки'});
Object.assign(gameWords.kk,{audio:'Аудиотапсырма',passage:'Дайын мәтін',scratch:'Қаралама',pencil:'Қарындаш',eraser:'Өшіргіш',clear:'Тазалау',listen:'Жазбаны тыңдап, жауапты таңдаңыз',ticketNav:'Билеттер'});
return {plainAnswer,languages,fonts,gameWords,screenDefaults,t,screenText,migrate,math,patch,httpsURL,embedCode};
})();
