class LotoTaskPeek {
  constructor(game){this.game=game;this.key=null;this.pinned=false;this.timer=null;this.ignoreFocus=false;}
  markup(){return `<section class="task-peek" id="task-peek" role="dialog" aria-label="${Loto.esc(this.game.t('taskDetails'))}" hidden><header><strong>${Loto.esc(this.game.t('taskDetails'))}</strong><button class="peek-close" aria-label="${Loto.esc(this.game.t('close'))}">×</button></header><div class="peek-fit" data-fit-box><div class="task-peek-content"></div></div></section>`;}
  open(key,pinned=false){clearTimeout(this.timer);const [tid,index]=key.split(':'),ticket=this.game.p.tickets.find(t=>t.id===tid),id=key.startsWith('bank:')?key.slice(5):ticket?.cells[Number(index)],q=this.game.p.questions.find(q=>q.id===id);if(!q)return this.close();this.key=key;this.pinned=pinned;this.refresh();}
  leave(){if(!this.pinned){clearTimeout(this.timer);this.timer=setTimeout(()=>this.close(),180);}}
  close(restoreFocus=false){clearTimeout(this.timer);const old=this.key;this.key=null;this.pinned=false;const panel=this.game.root.querySelector('.task-peek');if(panel){panel.hidden=true;panel.querySelectorAll('audio').forEach(audio=>audio.pause?.());}this.game.root.querySelectorAll('[data-cell]').forEach(b=>b.removeAttribute('aria-describedby'));if(restoreFocus){const button=[...this.game.root.querySelectorAll('[data-cell]')].find(b=>b.dataset.cell===old);this.ignoreFocus=true;button?.focus();this.ignoreFocus=false;}}
  refresh(){const panel=this.game.root.querySelector('.task-peek');if(!panel||!this.key)return;if(this.game.scratch.open||!['game','question'].includes(this.game.screen))return this.close();const [tid,index]=this.key.split(':'),ticket=this.game.p.tickets.find(t=>t.id===tid),id=this.key.startsWith('bank:')?this.key.slice(5):ticket?.cells[Number(index)],q=this.game.p.questions.find(q=>q.id===id);if(!q)return this.close();const anchor=[...this.game.root.querySelectorAll('[data-cell]')].find(b=>b.dataset.cell===this.key);if(!anchor&&!this.key.startsWith('bank:'))return this.close();const content=panel.querySelector('.task-peek-content');LotoUI.patch(content,`${q.passage?`<div class="reading-passage">${LotoUI.math(q.passage)}</div>`:''}<h3>${LotoUI.math(q.text)}</h3>${LotoMedia.html(q.media)}`);panel.hidden=false;anchor?.setAttribute('aria-describedby','task-peek');const rr=this.game.root.getBoundingClientRect(),r=anchor?.getBoundingClientRect()||rr,scale=rr.width/LotoViewport.WIDTH||1,w=560,h=330;const left=Math.max(16,Math.min(LotoViewport.WIDTH-w-16,(r.left-rr.left)/scale));const above=(r.top-rr.top)/scale-h-12,below=(r.bottom-rr.top)/scale+12;const top=Math.max(16,Math.min(LotoViewport.HEIGHT-h-16,above>=16?above:below));panel.style.left=left+'px';panel.style.top=top+'px';this.game.root.fitToViewport?.();}
  bind(){const panel=this.game.root.querySelector('.task-peek');if(!panel)return;panel.onpointerenter=()=>clearTimeout(this.timer);panel.onpointerleave=()=>this.leave();panel.querySelector('.peek-close').onclick=()=>this.close(true);this.game.root.onkeydown=e=>{if(e.key==='Escape'&&this.key){e.preventDefault();this.close(true);}};this.game.root.querySelectorAll('[data-cell]').forEach(cell=>{cell.onpointerenter=e=>{if(e.pointerType!=='touch'&&!LotoCellDrag.active&&!this.pinned)this.open(cell.dataset.cell);};cell.onpointerleave=()=>this.leave();cell.onfocus=()=>{if(!this.ignoreFocus&&!LotoCellDrag.active)this.open(cell.dataset.cell);};cell.onblur=e=>{if(!panel.contains(e.relatedTarget))this.leave();};});this.refresh();}
}
